//! The storyboard's vector icons (scripts/design.py SVG), generated by
//! scripts/gen_icons.py — do not edit. Served to the renderer from the
//! module's loopback asset server.
pub const ICONS: &[(&str, &str)] = &[
    ("ai_compose", r##"<rect x="8" y="6" width="14" height="14" rx="2"/><path d="M6 24l16-16M7 21l1.5 2.5M4.5 23.5l2.5-2.5"/><path d="M8 24l1 2 1-2 2-1-2-1-1-2-1 2-2 1z" fill="currentColor"/>"##),
    ("ai_compose_on", r##"<rect x="8" y="6" width="14" height="14" rx="2"/><path d="M8 24l1 2 1-2 2-1-2-1-1-2-1 2-2 1z" fill="currentColor"/><path d="M12 10h6v6"/>"##),
    ("flash_auto", r##"<path d="M13 4 7 16h5l-1 8 7-12h-5l1-8z" fill="currentColor"/><path d="M18 24l3-8 3 8M19.2 21.5h3.6" stroke-width="1.6"/>"##),
    ("flash_off", r##"<path d="M15 4 9 16h5l-1 8 7-12h-5l1-8z"/><path d="M6 6l16 16"/>"##),
    ("flash_on", r##"<path d="M15 4 9 16h5l-1 8 7-12h-5l1-8z" fill="currentColor"/>"##),
    ("flash_torch", r##"<path d="M9 13a5 5 0 0 1 10 0c0 3-2 3-2 6h-6c0-3-2-3-2-6z"/><path d="M12 22h4M12.5 25h3M14 3v3M5 13H2M26 13h-3M6.2 5.2l2.1 2.1M21.8 5.2l-2.1 2.1"/>"##),
    ("live_off", r##"<circle cx="14" cy="14" r="5"/><circle cx="14" cy="14" r="9" stroke-dasharray="1.4 2.2"/><path d="M6 6l16 16"/>"##),
    ("live_on", r##"<circle cx="14" cy="14" r="5"/><circle cx="14" cy="14" r="9" stroke-dasharray="1.4 2.2"/>"##),
    ("film", r##"<rect x="3" y="7" width="22" height="14" rx="2"/><path d="M3 11h22M3 17h22M7 7v4M12 7v4M17 7v4M22 7v4M7 17v4M12 17v4M17 17v4M22 17v4"/>"##),
    ("film_solid", r##"<rect x="3" y="7" width="22" height="14" rx="2" fill="currentColor"/><path d="M3 11h22M3 17h22" stroke="#111"/>"##),
    ("petal", r##"<circle cx="14" cy="14" r="2.5"/><path d="M14 4v6M14 18v6M4 14h6M18 14h6M7 7l4 4M17 17l4 4M21 7l-4 4M7 21l4-4"/>"##),
    ("switch_camera", r##"<path d="M9 9h3l2-3h4l2 3h3a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H9a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2z" fill="currentColor"/><circle cx="16" cy="15" r="3" fill="#111"/><path d="M5 22c1 3 5 4 9 4M23 22c-1 3-5 4-9 4M12 27l2-1-2-1"/>"##),
    ("video_camera", r##"<rect x="3" y="8" width="15" height="12" rx="3" fill="currentColor"/><path d="M18 12l7-4v12l-7-4z" fill="currentColor"/>"##),
    ("beauty", r##"<circle cx="14" cy="15" r="8"/><path d="M8 12c2-4 10-4 12 0M11 16h.5M16.5 16h.5M11 19c2 1.5 4 1.5 6 0"/><path d="M22 5l1 2 2 1-2 1-1 2-1-2-2-1 2-1z" fill="currentColor"/>"##),
    ("aperture", r##"<circle cx="14" cy="14" r="10"/><path d="M14 4v10l8.7 5M14 14l-8.7 5M5.3 9l8.7 5 8.7-5"/>"##),
    ("aperture_solid", r##"<circle cx="14" cy="14" r="10" fill="currentColor"/><circle cx="14" cy="14" r="4" fill="#111"/><path d="M14 4v6M14 18v6M5.3 9l5.2 3M17.5 16l5.2 3M22.7 9l-5.2 3M10.5 16l-5.2 3" stroke="#111"/>"##),
    ("info", r##"<circle cx="14" cy="14" r="10"/><path d="M14 12v7M14 8.5v.5"/>"##),
    ("moon", r##"<path d="M16 4a10 10 0 1 0 8 14 8 8 0 0 1-8-14z" fill="currentColor"/><path d="M21 5l1 2 2 1-2 1-1 2-1-2-2-1 2-1z" fill="currentColor"/>"##),
    ("shutter_s", r##"<path d="M18 8c-1-2-8-2-8 2s8 2 8 6-7 4-8 2" stroke-width="2.2"/>"##),
    ("gear", r##"<circle cx="14" cy="14" r="3.5"/><path d="M14 4v3m0 14v3M4 14h3m14 0h3M6.9 6.9l2.1 2.1m10 10 2.1 2.1M21.1 6.9 19 9m-10 10-2.1 2.1"/>"##),
    ("vision", r##"<path d="M6 11V8a2 2 0 0 1 2-2h3M17 6h3a2 2 0 0 1 2 2v3M22 17v3a2 2 0 0 1-2 2h-3M11 22H8a2 2 0 0 1-2-2v-3"/><circle cx="14" cy="14" r="4"/><path d="M8 4l.8 1.6L10.4 6.4 8.8 7.2 8 8.8 7.2 7.2 5.6 6.4 7.2 5.6z" fill="currentColor"/>"##),
    ("exposure", r##"<circle cx="14" cy="14" r="6"/><path d="M14 8a6 6 0 0 1 0 12z" fill="currentColor"/><path d="M14 3v3M14 22v3M3 14h3M22 14h3M6.2 6.2l2.1 2.1M19.7 19.7l2.1 2.1M21.8 6.2l-2.1 2.1M8.3 19.7l-2.1 2.1"/>"##),
    ("sun", r##"<circle cx="14" cy="14" r="5"/><path d="M14 3v3M14 22v3M3 14h3M22 14h3M6.2 6.2l2.1 2.1M19.7 19.7l2.1 2.1M21.8 6.2l-2.1 2.1M8.3 19.7l-2.1 2.1"/>"##),
    ("watermark", r##"<circle cx="14" cy="9" r="4"/><path d="M10 12l-2 6h12l-2-6M6 18v4h16v-4"/>"##),
    ("ratio", r##"<rect x="4" y="5" width="20" height="18" rx="3"/>"##),
    ("grid", r##"<path d="M10 4v20M18 4v20M4 10h20M4 18h20M6 6l16 16"/>"##),
    ("macro", r##"<path d="M14 14c-4 0-5-4-5-7 3 0 5 2 5 7zM14 14c4 0 5-4 5-7-3 0-5 2-5 7zM14 14v10M14 24c-3 0-6-2-6-5 3 0 6 2 6 5zM14 24c3 0 6-2 6-5-3 0-6 2-6 5z"/>"##),
    ("highres", r##"<circle cx="13" cy="13" r="8"/><path d="M19 19l5 5M10 10h2v2h-2zM14 10h2v2h-2zM10 14h2v2h-2zM14 14h2v2h-2z" fill="currentColor"/>"##),
    ("slowmo", r##"<path d="M14 4a10 10 0 1 1-8.7 5" /><circle cx="14" cy="14" r="2.5" fill="currentColor"/><circle cx="10" cy="14" r="2.5" fill="currentColor" opacity=".6"/><circle cx="6.5" cy="14" r="2.5" fill="currentColor" opacity=".3"/><path d="M6.2 6.2l1 1M4 10l1.2.6" stroke-dasharray="1 2"/>"##),
    ("timelapse", r##"<circle cx="14" cy="14" r="10"/><path d="M14 14l3-5M5 9l1 .5M4.5 13h1M5 17l1-.5" stroke-dasharray="1.2 2"/><circle cx="14" cy="14" r="1.4" fill="currentColor"/>"##),
    ("lightpaint", r##"<path d="M4 11h10M6 15h8M8 19h6"/><path d="M20 6l1.2 3 3 1.2-3 1.2-1.2 3-1.2-3-3-1.2 3-1.2z" fill="currentColor"/><path d="M22 18l.7 1.6 1.6.7-1.6.7-.7 1.6-.7-1.6-1.6-.7 1.6-.7z" fill="currentColor"/>"##),
    ("panorama", r##"<path d="M4 6c6 2 14 2 20 0v16c-6-2-14-2-20 0z"/><path d="M6 18l5-5 4 4 3-3 4 4"/><circle cx="18" cy="10" r="1.5" fill="currentColor"/>"##),
    ("chevron_up", r##"<path d="m6 18 8-8 8 8"/>"##),
    ("chevron_down", r##"<path d="m6 10 8 8 8-8"/>"##),
    ("check", r##"<path d="m6 14 6 6L23 8"/>"##),
    ("close", r##"<path d="m7 7 14 14M21 7 7 21"/>"##),
    ("pencil", r##"<path d="M5 23l1-5L18 6l4 4L10 22z"/><path d="M15 9l4 4"/>"##),
    ("reset", r##"<path d="M6 14a8 8 0 1 0 3-6.2M6 5v4h4"/>"##),
    ("stabilise", r##"<path d="M10 24V12a2 2 0 0 1 4 0v-3a2 2 0 0 1 4 0v3a2 2 0 0 1 4 0v8a6 6 0 0 1-6 6h-1a5 5 0 0 1-5-5zM10 15l-3-3a2 2 0 0 1 3-3"/><path d="M5 5l18 18"/>"##),
    ("sliders", r##"<path d="M4 9h20M4 19h20"/><circle cx="10" cy="9" r="2.5" fill="#111"/><circle cx="18" cy="19" r="2.5" fill="#111"/>"##),
    ("night_enhance", r##"<path d="M16 4a10 10 0 1 0 8 14 8 8 0 0 1-8-14z" fill="currentColor"/>"##),
    ("camera", r##"<path d="M9 9h3l2-3h4l2 3h3a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2z"/><circle cx="14" cy="15" r="3"/>"##),
    ("pause", r##"<path d="M10 7v14M18 7v14" stroke-width="3"/>"##),
    ("metering", r##"<rect x="4" y="8" width="20" height="12" rx="2"/><path d="M10 11l-2 3 2 3M18 11l2 3-2 3"/>"##),
    ("back", r##"<path d="m17 4-10 10 10 10"/>"##),
    ("arrow_left", r##"<path d="M24 14H8M13 8l-6 6 6 6" stroke-width="2.4"/>"##),
    ("arrow_right", r##"<path d="M4 14h16M15 8l6 6-6 6" stroke-width="2.4"/>"##),
    ("status", r##"<path d="M2 17v4m4-8v8m4-12v12m4-16v16M19 10q6-6 12 0m-9 3q3-3 6 0m-4 3h2M36 8h15v11H36zm17 3v5"/>"##),
];

/// One stroked icon file in the given hex colour (`rrggbb`).
pub fn svg(name: &str, color: &str) -> Option<String> {
    let body = ICONS.iter().find(|(n, _)| *n == name)?.1.replace("currentColor", &format!("#{color}"));
    let viewbox = if name == "status" { "0 0 56 28" } else { "0 0 28 28" };
    Some(format!(r##"<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}" fill="none" stroke="#{color}" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">{body}</svg>"##))
}
