// FROZEN compile of ⟶ [Profile] View #5 — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    RoundedView{ width: 375.0 height: 812.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 375.0 height: 812.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #140f2699 }
    RoundedView{ width: 355.0 height: 620.0 margin: Inset{left: 10.0 right: 0 top: 130.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 355.0 height: 300.0 margin: Inset{left: 10.0 right: 0 top: 129.5 bottom: 0} draw_bg.color: #bb92ecff draw_bg.color_2: #55c3b2ff }
    RoundedView{ width: 355.0 height: 390.5 margin: Inset{left: 10.0 right: 0 top: 359.5 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 80.0 height: 25.0 margin: Inset{left: 260.0 right: 0 top: 425.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 12.5 }
    View{ width: 76.4 height: 17.0 margin: Inset{left: 274.0 right: 0 top: 432.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Follow" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 63.0 height: 16.0 margin: Inset{left: 95.0 right: 0 top: 440.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Kolkata" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 128.8 height: 21.0 margin: Inset{left: 95.0 right: 0 top: 422.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Aasiya Jayavant" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 35.0 right: 0 top: 417.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 10.0 }
    RoundedView{ width: 80.0 height: 25.0 margin: Inset{left: 260.0 right: 0 top: 485.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 12.5 }
    View{ width: 76.4 height: 17.0 margin: Inset{left: 274.0 right: 0 top: 492.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Follow" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 63.0 height: 16.0 margin: Inset{left: 95.0 right: 0 top: 500.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Kraków" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 121.2 height: 21.0 margin: Inset{left: 95.0 right: 0 top: 482.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Ainara Vergara" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 35.0 right: 0 top: 477.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 10.0 }
    RoundedView{ width: 80.0 height: 25.0 margin: Inset{left: 260.0 right: 0 top: 545.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 12.5 }
    View{ width: 76.4 height: 17.0 margin: Inset{left: 274.0 right: 0 top: 552.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Follow" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 61.5 height: 16.0 margin: Inset{left: 95.0 right: 0 top: 560.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Lincoln" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 131.2 height: 21.0 margin: Inset{left: 95.0 right: 0 top: 542.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Justine Marshall" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 35.0 right: 0 top: 537.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 10.0 }
    RoundedView{ width: 80.0 height: 25.0 margin: Inset{left: 260.0 right: 0 top: 605.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 12.5 }
    View{ width: 76.4 height: 17.0 margin: Inset{left: 274.0 right: 0 top: 612.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Follow" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 66.5 height: 16.0 margin: Inset{left: 95.0 right: 0 top: 620.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Mumbai" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 111.5 height: 21.0 margin: Inset{left: 95.0 right: 0 top: 602.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Lew Silverton" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 35.0 right: 0 top: 597.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 10.0 }
    RoundedView{ width: 80.0 height: 25.0 margin: Inset{left: 260.0 right: 0 top: 665.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 12.5 }
    View{ width: 76.4 height: 17.0 margin: Inset{left: 274.0 right: 0 top: 672.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Follow" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 355.0 height: 1.0 margin: Inset{left: 10.0 right: 0 top: 706.5 bottom: 0} draw_bg.color: #ffffffff }
    View{ width: 57.0 height: 16.0 margin: Inset{left: 95.0 right: 0 top: 680.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Zurich" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 108.5 height: 21.0 margin: Inset{left: 95.0 right: 0 top: 662.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Yi Chun-Hwa" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 35.0 right: 0 top: 657.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 10.0 }
    View{ width: 165.6 height: 19.5 margin: Inset{left: 35.0 right: 0 top: 379.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "People you might know" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 63.5 height: 16.0 margin: Inset{left: 300.5 right: 0 top: 381.5 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "View all" draw_text.color: #5882f2ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 75.0 height: 75.0 margin: Inset{left: 150.0 right: 0 top: 179.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 18.8 }
    View{ width: 190.6 height: 21.0 margin: Inset{left: 111.5 right: 0 top: 302.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "San Francisco, California" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 190.0 height: 30.5 margin: Inset{left: 111.5 right: 0 top: 274.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Charles Davies" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 12.4 } } }
    RoundedView{ width: 30.0 height: 30.0 margin: Inset{left: 315.0 right: 0 top: 149.5 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 15.0 }
    RoundedView{ width: 10.3 height: 10.3 margin: Inset{left: 324.9 right: 0 top: 159.3 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 6.5 height: 6.5 margin: Inset{left: 326.8 right: 0 top: 161.3 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 337.4 right: 0 top: 775.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 337.4 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 220.6 height: 30.0 margin: Inset{left: 77.2 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 6.0 }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 1.4 }
    RoundedView{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 2.0 }
    RoundedView{ width: 14.0 height: 4.3 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.9 }
    RoundedView{ width: 9.1 height: 3.3 margin: Inset{left: 321.4 right: 0 top: 15.9 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.7 }
    RoundedView{ width: 4.2 height: 3.0 margin: Inset{left: 323.9 right: 0 top: 19.4 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.6 }
    RoundedView{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 1.9 }
    RoundedView{ width: 2.6 height: 3.5 margin: Inset{left: 299.0 right: 0 top: 18.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 5.2 margin: Inset{left: 303.1 right: 0 top: 17.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 7.2 margin: Inset{left: 307.2 right: 0 top: 15.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 9.2 margin: Inset{left: 311.4 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    View{ width: 67.0 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
}
