// FROZEN compile of ⟶ [Profile] View #6 — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    RoundedView{ width: 375.0 height: 812.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 375.0 height: 75.0 margin: Inset{left: 0.0 right: 0 top: 737.0 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 375.0 height: 1.4 margin: Inset{left: 0.0 right: 0 top: 737.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 49.0 height: 21.6 margin: Inset{left: 318.0 right: 0 top: 784.8 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "item label" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 325.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 49.0 height: 21.6 margin: Inset{left: 243.0 right: 0 top: 784.8 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "item label" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 250.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 49.0 height: 21.6 margin: Inset{left: 168.0 right: 0 top: 784.8 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "item label" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 175.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 15.5 height: 18.4 margin: Inset{left: 191.0 right: 0 top: 746.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 3.5 }
    View{ width: 21.9 height: 20.2 margin: Inset{left: 193.2 right: 0 top: 750.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "10" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 49.0 height: 21.6 margin: Inset{left: 93.0 right: 0 top: 784.8 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "item label" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 100.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 49.0 height: 21.6 margin: Inset{left: 18.0 right: 0 top: 784.8 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "item label" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 25.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 375.0 height: 812.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #140f2680 }
    RoundedView{ width: 375.0 height: 666.4 margin: Inset{left: 0.5 right: 0 top: 148.2 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 75.0 }
    RoundedView{ width: 313.0 height: 55.5 margin: Inset{left: 31.5 right: 0 top: 148.2 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 11.1 }
    RoundedView{ width: 375.0 height: 623.0 margin: Inset{left: 0.5 right: 0 top: 191.5 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 125.5 height: 165.0 margin: Inset{left: 25.5 right: 0 top: 564.0 bottom: 0} draw_bg.color: #0f0f0fff draw_bg.border_radius: 5.0 }
    RoundedView{ width: 125.5 height: 165.0 margin: Inset{left: 161.0 right: 0 top: 564.0 bottom: 0} draw_bg.color: #0f0f0fff draw_bg.border_radius: 5.0 }
    RoundedView{ width: 125.5 height: 165.0 margin: Inset{left: 296.5 right: 0 top: 564.0 bottom: 0} draw_bg.color: #0f0f0fff draw_bg.border_radius: 5.0 }
    View{ width: 114.5 height: 19.5 margin: Inset{left: 25.5 right: 0 top: 536.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Favourite places" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 126.9 height: 21.0 margin: Inset{left: 137.0 right: 0 top: 311.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Berlin, Germany" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 210.6 height: 30.5 margin: Inset{left: 103.2 right: 0 top: 284.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Maria José Botín" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 12.4 } } }
    View{ width: 335.0 height: 51.5 margin: Inset{left: 25.0 right: 0 top: 336.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "Typical thinker. Incurable tv geek. Explorer. Friend of animals everywhere. Entrepreneur." draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 150.0 height: 40.0 margin: Inset{left: 112.5 right: 0 top: 392.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 6.0 }
    RoundedView{ width: 24.0 height: 19.2 margin: Inset{left: 128.5 right: 0 top: 402.4 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 112.0 height: 14.0 margin: Inset{left: 158.5 right: 0 top: 408.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "message" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    View{ width: 77.0 height: 19.0 margin: Inset{left: 50.5 right: 0 top: 494.6 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Followers" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 37.5 height: 28.0 margin: Inset{left: 63.2 right: 0 top: 473.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "35k" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    View{ width: 62.0 height: 19.0 margin: Inset{left: 168.5 right: 0 top: 494.6 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Stories" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 33.5 height: 28.0 margin: Inset{left: 175.8 right: 0 top: 473.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "315" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    View{ width: 78.5 height: 19.0 margin: Inset{left: 270.8 right: 0 top: 494.6 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Following" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 40.0 height: 28.0 margin: Inset{left: 282.8 right: 0 top: 473.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "1931" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 455.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 231.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 100.0 height: 100.0 margin: Inset{left: 137.5 right: 0 top: 162.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 50.0 }
    RoundedView{ width: 48.0 height: 16.0 margin: Inset{left: 163.5 right: 0 top: 252.5 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 4.0 }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 195.0 right: 0 top: 253.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 49.0 height: 15.0 margin: Inset{left: 167.5 right: 0 top: 256.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "LIVE" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #121217eb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 337.4 right: 0 top: 775.0 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #121217ff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 337.4 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 220.6 height: 30.0 margin: Inset{left: 77.2 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 6.0 }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 1.4 }
    RoundedView{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 2.0 }
    RoundedView{ width: 14.0 height: 4.3 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.9 }
    RoundedView{ width: 9.1 height: 3.3 margin: Inset{left: 321.4 right: 0 top: 15.9 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.7 }
    RoundedView{ width: 4.2 height: 3.0 margin: Inset{left: 323.9 right: 0 top: 19.4 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.6 }
    RoundedView{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 1.9 }
    RoundedView{ width: 2.6 height: 3.5 margin: Inset{left: 299.0 right: 0 top: 18.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 5.2 margin: Inset{left: 303.1 right: 0 top: 17.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 7.2 margin: Inset{left: 307.2 right: 0 top: 15.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 9.2 margin: Inset{left: 311.4 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    View{ width: 67.0 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
    RoundedView{ width: 375.0 height: 90.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 20.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff856 }
}
