// FROZEN compile of ⟶ [Shop] View #17 — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    RoundedView{ width: 375.0 height: 90.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 331.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 20.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 114.0 height: 18.9 margin: Inset{left: 59.0 right: 0 top: 36.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Checkout" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    RoundedView{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #121217eb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 337.4 right: 0 top: 775.0 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #121217ff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217eb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 337.4 right: 0 top: 0.0 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 220.6 height: 30.0 margin: Inset{left: 77.2 right: 0 top: 0.0 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 6.0 }
    View{ width: 67.0 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #131315ff draw_bg.border_radius: 1.4 }
    RoundedView{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #121217eb draw_bg.border_radius: 2.0 }
    RoundedView{ width: 14.0 height: 4.3 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 0.9 }
    RoundedView{ width: 9.1 height: 3.3 margin: Inset{left: 321.4 right: 0 top: 15.9 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 0.7 }
    RoundedView{ width: 4.2 height: 3.0 margin: Inset{left: 323.9 right: 0 top: 19.4 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 0.6 }
    RoundedView{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} draw_bg.color: #121217eb draw_bg.border_radius: 1.9 }
    RoundedView{ width: 2.6 height: 3.5 margin: Inset{left: 299.0 right: 0 top: 18.8 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 5.2 margin: Inset{left: 303.1 right: 0 top: 17.1 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 7.2 margin: Inset{left: 307.2 right: 0 top: 15.1 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 9.2 margin: Inset{left: 311.4 right: 0 top: 13.0 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 335.0 height: 40.0 margin: Inset{left: 20.0 right: 0 top: 194.0 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 7.5 }
    View{ width: 78.0 height: 16.0 margin: Inset{left: 30.0 right: 0 top: 209.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Maria José Botín" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 418.8 height: 15.0 margin: Inset{left: 20.0 right: 0 top: 180.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Name" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 178.8 height: 17.0 margin: Inset{left: 20.0 right: 0 top: 152.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Contact information" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 160.0 height: 40.0 margin: Inset{left: 20.0 right: 0 top: 265.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 3.6 draw_bg.border_size: 1.0 draw_bg.border_color: #5882f2ff }
    View{ width: 49.8 height: 16.0 margin: Inset{left: 24.8 right: 0 top: 280.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "maria@email.com" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 200.0 height: 15.0 margin: Inset{left: 20.0 right: 0 top: 251.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Email address" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 160.0 height: 40.0 margin: Inset{left: 195.0 right: 0 top: 265.0 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 3.6 }
    View{ width: 49.8 height: 16.0 margin: Inset{left: 199.8 right: 0 top: 280.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Enter number" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 200.0 height: 15.0 margin: Inset{left: 195.0 right: 0 top: 251.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Phone number" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 335.0 height: 40.0 margin: Inset{left: 20.0 right: 0 top: 448.0 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 7.5 }
    View{ width: 78.0 height: 16.0 margin: Inset{left: 30.0 right: 0 top: 463.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Enter your address" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 418.8 height: 15.0 margin: Inset{left: 20.0 right: 0 top: 434.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Street Address" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 147.5 height: 17.0 margin: Inset{left: 20.0 right: 0 top: 335.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Delivery address" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 160.0 height: 40.0 margin: Inset{left: 20.0 right: 0 top: 377.0 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 3.6 }
    RoundedView{ width: 7.2 height: 15.0 margin: Inset{left: 168.3 right: 0 top: 390.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 49.8 height: 16.0 margin: Inset{left: 24.8 right: 0 top: 392.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "New York" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 200.0 height: 15.0 margin: Inset{left: 20.0 right: 0 top: 363.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "City" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 160.0 height: 40.0 margin: Inset{left: 195.0 right: 0 top: 377.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 3.6 draw_bg.border_size: 1.0 draw_bg.border_color: #ff8b8cff }
    RoundedView{ width: 7.2 height: 15.0 margin: Inset{left: 343.3 right: 0 top: 390.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 49.8 height: 16.0 margin: Inset{left: 199.8 right: 0 top: 392.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Enter Zipcode" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 200.0 height: 15.0 margin: Inset{left: 195.0 right: 0 top: 363.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Zip code" draw_text.color: #d84242ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 155.0 height: 17.0 margin: Inset{left: 20.0 right: 0 top: 518.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Delivery interval" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 100.0 height: 90.0 margin: Inset{left: 20.0 right: 0 top: 544.0 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 7.5 }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 35.0 right: 0 top: 554.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 66.5 height: 21.0 margin: Inset{left: 35.0 right: 0 top: 609.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$12.99" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 57.5 height: 16.0 margin: Inset{left: 35.0 right: 0 top: 581.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Today" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 87.5 height: 15.5 margin: Inset{left: 35.0 right: 0 top: 593.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "14:00 - 18:00" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 100.0 height: 90.0 margin: Inset{left: 137.5 right: 0 top: 544.0 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 7.5 }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 152.5 right: 0 top: 554.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 62.5 height: 21.0 margin: Inset{left: 152.5 right: 0 top: 609.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$8.99" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 79.5 height: 16.0 margin: Inset{left: 152.5 right: 0 top: 581.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Tomorrow" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 89.0 height: 15.5 margin: Inset{left: 152.5 right: 0 top: 593.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "09:00 - 21:00" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 100.0 height: 90.0 margin: Inset{left: 255.0 right: 0 top: 544.0 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 7.5 }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 270.0 right: 0 top: 554.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 53.0 height: 21.0 margin: Inset{left: 270.0 right: 0 top: 609.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Free" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 81.0 height: 16.0 margin: Inset{left: 270.0 right: 0 top: 581.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Next week" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 79.0 height: 15.5 margin: Inset{left: 270.0 right: 0 top: 593.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Mon - Tue" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 335.0 height: 40.0 margin: Inset{left: 20.0 right: 0 top: 707.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 6.0 }
    View{ width: 245.7 height: 14.0 margin: Inset{left: 122.8 right: 0 top: 723.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "continue" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    RoundedView{ width: 375.0 height: 40.0 margin: Inset{left: 0.0 right: 0 top: 90.0 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 19.8 height: 18.0 margin: Inset{left: 80.1 right: 0 top: 85.5 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 9.0 }
    RoundedView{ width: 16.5 height: 15.0 margin: Inset{left: 81.8 right: 0 top: 87.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 51.0 height: 16.0 margin: Inset{left: 76.5 right: 0 top: 109.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Delivery" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 25.2 height: 18.0 margin: Inset{left: 174.9 right: 0 top: 85.5 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 9.0 }
    RoundedView{ width: 21.0 height: 15.0 margin: Inset{left: 177.0 right: 0 top: 87.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 58.3 height: 16.0 margin: Inset{left: 170.3 right: 0 top: 109.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Confirmation" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 19.8 height: 18.0 margin: Inset{left: 275.1 right: 0 top: 85.5 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 9.0 }
    RoundedView{ width: 16.5 height: 15.0 margin: Inset{left: 276.8 right: 0 top: 87.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 51.0 height: 16.0 margin: Inset{left: 271.6 right: 0 top: 109.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Payment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 129.0 bottom: 0} draw_bg.color: #f4f6f9ff }
}
