// FROZEN compile of ⟶ [Social] Feed #4 — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    RoundedView{ width: 375.0 height: 812.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 355.0 height: 363.5 margin: Inset{left: 10.0 right: 0 top: 458.5 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 10.0 }
    RoundedView{ width: 330.0 height: 204.0 margin: Inset{left: 22.5 right: 0 top: 574.0 bottom: 0} draw_bg.color: #d7dfffff draw_bg.border_radius: 5.0 }
    View{ width: 51.0 height: 16.0 margin: Inset{left: 40.4 right: 0 top: 795.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Like" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 10.4 height: 15.0 margin: Inset{left: 30.0 right: 0 top: 792.5 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 56.5 height: 16.0 margin: Inset{left: 310.0 right: 0 top: 795.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Share" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 12.5 height: 15.0 margin: Inset{left: 297.5 right: 0 top: 792.5 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 71.9 height: 16.0 margin: Inset{left: 107.9 right: 0 top: 795.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Comment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 18.4 height: 15.0 margin: Inset{left: 89.5 right: 0 top: 792.5 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 325.0 height: 36.0 margin: Inset{left: 30.0 right: 0 top: 524.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "It’s hard to say when in our lives each of us become aware of this thing called “astronomy”." draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 65.0 height: 16.0 margin: Inset{left: 288.1 right: 0 top: 481.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Phoenix" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 15.8 height: 15.0 margin: Inset{left: 329.2 right: 0 top: 478.5 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 68.5 height: 16.0 margin: Inset{left: 75.0 right: 0 top: 496.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "06:02PM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 90.0 height: 17.0 margin: Inset{left: 75.0 right: 0 top: 481.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Dale Hogan" draw_text.color: #5882f2ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 30.0 height: 30.0 margin: Inset{left: 30.0 right: 0 top: 478.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 15.0 }
    RoundedView{ width: 355.0 height: 363.5 margin: Inset{left: 10.0 right: 0 top: 90.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 10.0 }
    RoundedView{ width: 330.0 height: 204.0 margin: Inset{left: 22.5 right: 0 top: 205.5 bottom: 0} draw_bg.color: #d7dfffff draw_bg.border_radius: 5.0 }
    View{ width: 51.0 height: 16.0 margin: Inset{left: 40.4 right: 0 top: 426.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Like" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 10.4 height: 15.0 margin: Inset{left: 30.0 right: 0 top: 424.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 56.5 height: 16.0 margin: Inset{left: 310.0 right: 0 top: 426.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Share" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 12.5 height: 15.0 margin: Inset{left: 297.5 right: 0 top: 424.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 71.9 height: 16.0 margin: Inset{left: 107.9 right: 0 top: 426.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Comment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 18.4 height: 15.0 margin: Inset{left: 89.5 right: 0 top: 424.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 325.0 height: 36.0 margin: Inset{left: 30.0 right: 0 top: 155.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "It’s hard to say when in our lives each of us become aware of this thing called “astronomy”." draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 65.0 height: 16.0 margin: Inset{left: 288.1 right: 0 top: 112.5 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Phoenix" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 15.8 height: 15.0 margin: Inset{left: 329.2 right: 0 top: 110.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 68.5 height: 16.0 margin: Inset{left: 75.0 right: 0 top: 127.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "01:13AM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 90.0 height: 17.0 margin: Inset{left: 75.0 right: 0 top: 113.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Billy Tucker" draw_text.color: #5882f2ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 30.0 height: 30.0 margin: Inset{left: 30.0 right: 0 top: 110.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 15.0 }
    RoundedView{ width: 375.0 height: 90.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 331.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 20.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 114.0 height: 18.9 margin: Inset{left: 142.5 right: 0 top: 36.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Trending" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    RoundedView{ width: 7.0 height: 7.0 margin: Inset{left: 346.5 right: 0 top: 50.5 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 3.5 }
    RoundedView{ width: 164.5 height: 45.0 margin: Inset{left: 105.2 right: 0 top: 712.0 bottom: 0} draw_bg.color: #140f2680 draw_bg.border_radius: 22.5 }
    RoundedView{ width: 18.4 height: 24.0 margin: Inset{left: 239.9 right: 0 top: 722.5 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 107.0 height: 16.0 margin: Inset{left: 120.5 right: 0 top: 729.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "New post available" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 337.4 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 220.6 height: 30.0 margin: Inset{left: 77.2 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 6.0 }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 1.4 }
    RoundedView{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 2.0 }
    RoundedView{ width: 14.0 height: 4.3 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.9 }
    RoundedView{ width: 9.1 height: 3.3 margin: Inset{left: 321.4 right: 0 top: 15.9 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.7 }
    RoundedView{ width: 4.2 height: 3.0 margin: Inset{left: 323.9 right: 0 top: 19.4 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.6 }
    RoundedView{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 1.9 }
    RoundedView{ width: 2.6 height: 3.5 margin: Inset{left: 299.0 right: 0 top: 18.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 5.2 margin: Inset{left: 303.1 right: 0 top: 17.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 7.2 margin: Inset{left: 307.2 right: 0 top: 15.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 9.2 margin: Inset{left: 311.4 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    View{ width: 67.0 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
    RoundedView{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 337.4 right: 0 top: 775.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
}
