// FROZEN compile of ⟶ [Stats] Cards — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    RoundedView{ width: 375.0 height: 812.0 margin: Inset{left: 0.0 right: 0 top: 0.5 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 335.0 height: 220.0 margin: Inset{left: 20.0 right: 0 top: 90.0 bottom: 0} draw_bg.color: #45e994ff draw_bg.color_2: #23bcbaff draw_bg.border_radius: 15.0 }
    RoundedView{ width: 28.0 height: 20.0 margin: Inset{left: 312.0 right: 0 top: 265.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 4.0 }
    RoundedView{ width: 28.0 height: 20.0 margin: Inset{left: 312.0 right: 0 top: 265.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 4.0 }
    RoundedView{ width: 24.5 height: 6.1 margin: Inset{left: 313.8 right: 0 top: 272.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 1.2 }
    RoundedView{ width: 11.7 height: 4.3 margin: Inset{left: 315.2 right: 0 top: 273.6 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.9 }
    RoundedView{ width: 8.4 height: 4.3 margin: Inset{left: 327.9 right: 0 top: 273.6 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.9 }
    RoundedView{ width: 1.5 height: 1.8 margin: Inset{left: 317.2 right: 0 top: 274.4 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.3 }
    RoundedView{ width: 3.9 height: 2.5 margin: Inset{left: 328.9 right: 0 top: 274.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    View{ width: 111.5 height: 15.0 margin: Inset{left: 45.0 right: 0 top: 121.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "card balance" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 164.4 height: 41.0 margin: Inset{left: 45.0 right: 0 top: 133.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$235.00" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 18.6 } } }
    View{ width: 203.5 height: 28.0 margin: Inset{left: 45.0 right: 0 top: 217.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "3713 5878 2833 34195" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    View{ width: 64.0 height: 15.0 margin: Inset{left: 45.0 right: 0 top: 257.8 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Expire" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 52.5 height: 28.0 margin: Inset{left: 45.0 right: 0 top: 269.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "12/24" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    View{ width: 47.0 height: 15.0 margin: Inset{left: 122.0 right: 0 top: 258.6 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "CVV" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 38.0 height: 28.0 margin: Inset{left: 122.0 right: 0 top: 269.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "235" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 316.0 right: 0 top: 104.4 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 335.0 height: 220.0 margin: Inset{left: 20.0 right: 0 top: 320.0 bottom: 0} draw_bg.color: #ccd1d9ff draw_bg.color_2: #8f9aa8ff draw_bg.border_radius: 15.0 }
    View{ width: 196.5 height: 28.0 margin: Inset{left: 45.0 right: 0 top: 447.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "5326 5149 4497 1577" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    View{ width: 64.0 height: 15.0 margin: Inset{left: 45.0 right: 0 top: 487.8 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Expire" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 52.5 height: 28.0 margin: Inset{left: 45.0 right: 0 top: 499.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "12/24" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    View{ width: 47.0 height: 15.0 margin: Inset{left: 122.0 right: 0 top: 487.8 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "CVV" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 38.0 height: 28.0 margin: Inset{left: 122.0 right: 0 top: 499.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "235" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    RoundedView{ width: 34.0 height: 20.0 margin: Inset{left: 306.0 right: 0 top: 495.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 4.0 }
    RoundedView{ width: 1.6 height: 2.2 margin: Inset{left: 333.4 right: 0 top: 505.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.3 }
    RoundedView{ width: 1.0 height: 1.0 margin: Inset{left: 336.4 right: 0 top: 507.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 1.4 height: 1.0 margin: Inset{left: 321.5 right: 0 top: 505.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 1.0 height: 1.0 margin: Inset{left: 336.2 right: 0 top: 507.6 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 1.0 height: 1.0 margin: Inset{left: 336.4 right: 0 top: 507.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 34.0 height: 20.0 margin: Inset{left: 306.0 right: 0 top: 495.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 4.0 }
    RoundedView{ width: 3.5 height: 1.1 margin: Inset{left: 321.4 right: 0 top: 499.4 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 5.7 height: 1.1 margin: Inset{left: 320.2 right: 0 top: 501.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 6.2 height: 4.8 margin: Inset{left: 310.4 right: 0 top: 503.4 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 1.0 }
    RoundedView{ width: 3.8 height: 4.0 margin: Inset{left: 316.2 right: 0 top: 504.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.8 }
    RoundedView{ width: 3.7 height: 4.1 margin: Inset{left: 320.2 right: 0 top: 504.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.7 }
    RoundedView{ width: 4.8 height: 1.1 margin: Inset{left: 320.6 right: 0 top: 510.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 3.4 height: 4.0 margin: Inset{left: 323.9 right: 0 top: 504.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.7 }
    RoundedView{ width: 2.4 height: 4.9 margin: Inset{left: 327.2 right: 0 top: 503.4 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 3.1 height: 4.0 margin: Inset{left: 329.4 right: 0 top: 504.2 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.6 }
    RoundedView{ width: 4.3 height: 4.2 margin: Inset{left: 332.1 right: 0 top: 504.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.8 }
    RoundedView{ width: 1.0 height: 1.0 margin: Inset{left: 336.1 right: 0 top: 507.6 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 1.3 height: 1.0 margin: Inset{left: 317.4 right: 0 top: 506.4 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    View{ width: 111.5 height: 15.0 margin: Inset{left: 45.0 right: 0 top: 347.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "card balance" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 221.9 height: 41.0 margin: Inset{left: 45.0 right: 0 top: 361.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$12,929.05" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 18.6 } } }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 316.0 right: 0 top: 334.4 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 335.0 height: 220.0 margin: Inset{left: 20.0 right: 0 top: 550.0 bottom: 0} draw_bg.color: #9d61fdff draw_bg.color_2: #efbfd5ff draw_bg.border_radius: 15.0 }
    View{ width: 208.0 height: 28.0 margin: Inset{left: 45.0 right: 0 top: 677.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "4485 0961 4849 8888" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    View{ width: 64.0 height: 15.0 margin: Inset{left: 45.0 right: 0 top: 717.8 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Expire" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 52.5 height: 28.0 margin: Inset{left: 45.0 right: 0 top: 729.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "12/24" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    View{ width: 47.0 height: 15.0 margin: Inset{left: 122.0 right: 0 top: 717.8 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "CVV" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 38.0 height: 28.0 margin: Inset{left: 122.0 right: 0 top: 729.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "235" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    RoundedView{ width: 40.0 height: 12.5 margin: Inset{left: 300.0 right: 0 top: 737.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 2.5 }
    RoundedView{ width: 11.7 height: 12.1 margin: Inset{left: 328.4 right: 0 top: 737.7 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 2.3 }
    RoundedView{ width: 2.7 height: 4.5 margin: Inset{left: 333.4 right: 0 top: 741.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 9.8 height: 12.5 margin: Inset{left: 319.2 right: 0 top: 737.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 2.0 }
    RoundedView{ width: 7.6 height: 6.3 margin: Inset{left: 300.0 right: 0 top: 737.6 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 1.3 }
    RoundedView{ width: 11.4 height: 12.1 margin: Inset{left: 303.2 right: 0 top: 737.7 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 2.3 }
    RoundedView{ width: 5.3 height: 12.1 margin: Inset{left: 314.0 right: 0 top: 737.7 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 1.1 }
    View{ width: 111.5 height: 15.0 margin: Inset{left: 45.0 right: 0 top: 577.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "card balance" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 196.9 height: 41.0 margin: Inset{left: 45.0 right: 0 top: 591.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$3,841.84" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 18.6 } } }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 316.0 right: 0 top: 560.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 375.0 height: 94.5 margin: Inset{left: 0.0 right: 0 top: -4.5 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 24.0 height: 32.4 margin: Inset{left: 331.0 right: 0 top: 33.3 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 24.0 height: 32.4 margin: Inset{left: 20.0 right: 0 top: 33.3 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 49.0 height: 21.5 margin: Inset{left: 168.0 right: 0 top: 52.2 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "subtitle" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 114.0 height: 19.5 margin: Inset{left: 142.5 right: 0 top: 33.3 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "My virtual cards" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    RoundedView{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 337.4 right: 0 top: 775.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 337.4 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 220.6 height: 30.0 margin: Inset{left: 77.2 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 6.0 }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 1.4 }
    RoundedView{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 2.0 }
    RoundedView{ width: 14.0 height: 4.3 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.9 }
    RoundedView{ width: 9.1 height: 3.3 margin: Inset{left: 321.4 right: 0 top: 15.9 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.7 }
    RoundedView{ width: 4.2 height: 3.0 margin: Inset{left: 323.9 right: 0 top: 19.4 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.6 }
    RoundedView{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 1.9 }
    RoundedView{ width: 2.6 height: 3.5 margin: Inset{left: 299.0 right: 0 top: 18.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 5.2 margin: Inset{left: 303.1 right: 0 top: 17.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 7.2 margin: Inset{left: 307.2 right: 0 top: 15.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 9.2 margin: Inset{left: 311.4 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    View{ width: 67.0 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
}
