// FROZEN compile of ⟶ [Stats] Data visualization #2 — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    RoundedView{ width: 375.0 height: 667.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 375.0 height: 90.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 375.0 height: 1.3 margin: Inset{left: 0.0 right: 0 top: 88.7 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 20.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 114.0 height: 18.9 margin: Inset{left: 59.0 right: 0 top: 36.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "My Budget" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    View{ width: 49.0 height: 20.9 margin: Inset{left: 58.5 right: 0 top: 54.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "subtitle" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 329.0 right: 0 top: 52.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 8.2 height: 4.0 margin: Inset{left: 332.4 right: 0 top: 58.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.8 }
    View{ width: 62.0 height: 17.0 margin: Inset{left: 291.0 right: 0 top: 54.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "6 months" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 375.0 height: 230.0 margin: Inset{left: 0.0 right: 0 top: 90.0 bottom: 0} draw_bg.color: #ffffffff }
    View{ width: 165.6 height: 17.0 margin: Inset{left: 40.0 right: 0 top: 127.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$52721" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 69.0 height: 28.0 margin: Inset{left: 40.0 right: 0 top: 105.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "Savings" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    RoundedView{ width: 10.0 height: 10.0 margin: Inset{left: 20.0 right: 0 top: 112.5 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.border_radius: 5.0 }
    View{ width: 47.5 height: 17.0 margin: Inset{left: 20.0 right: 0 top: 161.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "100" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 51.0 height: 17.0 margin: Inset{left: 20.0 right: 0 top: 212.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "50" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 47.5 height: 17.0 margin: Inset{left: 20.0 right: 0 top: 263.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "0" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 335.0 height: 1.0 margin: Inset{left: 20.0 right: 0 top: 228.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 335.0 height: 1.0 margin: Inset{left: 20.0 right: 0 top: 177.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 51.0 height: 17.0 margin: Inset{left: 19.0 right: 0 top: 293.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Jan" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 48.0 height: 17.0 margin: Inset{left: 332.2 right: 0 top: 293.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Jun" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 49.5 height: 17.0 margin: Inset{left: 269.5 right: 0 top: 293.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "May" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 48.5 height: 17.0 margin: Inset{left: 207.5 right: 0 top: 293.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Apr" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 50.5 height: 17.0 margin: Inset{left: 143.5 right: 0 top: 293.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Mar" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 47.5 height: 17.0 margin: Inset{left: 83.0 right: 0 top: 293.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Feb" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 330.5 height: 116.5 margin: Inset{left: 49.0 right: 0 top: 167.0 bottom: 0} draw_bg.color: #1ad4ddff draw_bg.color_2: #ffffffff draw_bg.border_radius: 23.3 }
    RoundedShadowView{ width: 12.5 height: 12.5 margin: Inset{left: 92.5 right: 0 top: 203.0 bottom: 0} draw_bg.shadow_color: #24306fcd draw_bg.shadow_radius: 5.0 draw_bg.shadow_offset: vec2(0.0, 3.5) draw_bg.color: #ffffffff draw_bg.border_radius: 6.2 draw_bg.border_size: 2.0 draw_bg.border_color: #0cdfefff }
    RoundedView{ width: 33.0 height: 20.0 margin: Inset{left: 104.0 right: 0 top: 173.0 bottom: 0} draw_bg.color: #140f2693 draw_bg.border_radius: 3.6 }
    RoundedView{ width: 5.8 height: 10.0 margin: Inset{left: 104.0 right: 0 top: 188.0 bottom: 0} draw_bg.color: #140f2693 }
    RoundedView{ width: 33.0 height: 25.0 margin: Inset{left: 104.0 right: 0 top: 173.0 bottom: 0} draw_bg.color: #140f2675 draw_bg.border_radius: 5.0 }
    RoundedView{ width: 33.0 height: 20.0 margin: Inset{left: 104.0 right: 0 top: 173.0 bottom: 0} draw_bg.color: #140f2693 draw_bg.border_radius: 3.6 }
    RoundedView{ width: 5.8 height: 10.0 margin: Inset{left: 104.0 right: 0 top: 188.0 bottom: 0} draw_bg.color: #140f2693 }
    View{ width: 51.9 height: 17.0 margin: Inset{left: 106.5 right: 0 top: 177.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$139" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 319.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 375.0 height: 230.0 margin: Inset{left: 0.0 right: 0 top: 320.0 bottom: 0} draw_bg.color: #ffffffff }
    View{ width: 165.6 height: 17.0 margin: Inset{left: 40.0 right: 0 top: 357.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$75948" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 82.0 height: 28.0 margin: Inset{left: 40.0 right: 0 top: 335.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "Expenses" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    RoundedView{ width: 10.0 height: 10.0 margin: Inset{left: 20.0 right: 0 top: 341.5 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 5.0 }
    View{ width: 47.5 height: 17.0 margin: Inset{left: 20.0 right: 0 top: 391.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "100" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 51.0 height: 17.0 margin: Inset{left: 20.0 right: 0 top: 442.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "50" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 47.5 height: 17.0 margin: Inset{left: 20.0 right: 0 top: 493.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "0" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 335.0 height: 1.0 margin: Inset{left: 20.0 right: 0 top: 458.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 335.0 height: 1.0 margin: Inset{left: 20.0 right: 0 top: 407.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 51.0 height: 17.0 margin: Inset{left: 19.0 right: 0 top: 525.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Jan" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 48.0 height: 17.0 margin: Inset{left: 332.2 right: 0 top: 525.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Jun" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 49.5 height: 17.0 margin: Inset{left: 269.5 right: 0 top: 525.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "May" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 48.5 height: 17.0 margin: Inset{left: 207.5 right: 0 top: 525.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Apr" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 50.5 height: 17.0 margin: Inset{left: 143.5 right: 0 top: 525.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Mar" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 47.5 height: 17.0 margin: Inset{left: 83.0 right: 0 top: 525.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Feb" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 347.0 height: 113.3 margin: Inset{left: 49.5 right: 0 top: 402.5 bottom: 0} draw_bg.color: #ff7e8dff draw_bg.color_2: #ffffffff draw_bg.border_radius: 22.7 }
    RoundedShadowView{ width: 12.5 height: 12.5 margin: Inset{left: 139.0 right: 0 top: 431.5 bottom: 0} draw_bg.shadow_color: #24306fcd draw_bg.shadow_radius: 5.0 draw_bg.shadow_offset: vec2(0.0, 3.5) draw_bg.color: #ffffffff draw_bg.border_radius: 6.2 draw_bg.border_size: 2.0 draw_bg.border_color: #ff6686ff }
    RoundedView{ width: 51.5 height: 20.0 margin: Inset{left: 151.0 right: 0 top: 401.5 bottom: 0} draw_bg.color: #140f2693 draw_bg.border_radius: 5.0 }
    RoundedView{ width: 9.2 height: 10.0 margin: Inset{left: 151.0 right: 0 top: 416.5 bottom: 0} draw_bg.color: #140f2693 }
    RoundedView{ width: 51.5 height: 25.0 margin: Inset{left: 151.0 right: 0 top: 401.5 bottom: 0} draw_bg.color: #140f2675 draw_bg.border_radius: 5.0 }
    RoundedView{ width: 51.5 height: 20.0 margin: Inset{left: 151.0 right: 0 top: 401.5 bottom: 0} draw_bg.color: #140f2693 draw_bg.border_radius: 5.0 }
    RoundedView{ width: 9.2 height: 10.0 margin: Inset{left: 151.0 right: 0 top: 416.5 bottom: 0} draw_bg.color: #140f2693 }
    View{ width: 67.5 height: 17.0 margin: Inset{left: 155.0 right: 0 top: 406.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$287.22" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 549.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 375.0 height: 265.0 margin: Inset{left: 0.0 right: 0 top: 550.0 bottom: 0} draw_bg.color: #ffffffff }
    View{ width: 165.6 height: 17.0 margin: Inset{left: 40.0 right: 0 top: 587.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$8786" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 105.0 height: 28.0 margin: Inset{left: 40.0 right: 0 top: 565.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "Investments" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    RoundedView{ width: 10.0 height: 10.0 margin: Inset{left: 20.0 right: 0 top: 571.5 bottom: 0} draw_bg.color: #645affff draw_bg.color_2: #a573ffff draw_bg.gradient_fill_horizontal: 1.0 draw_bg.border_radius: 5.0 }
    View{ width: 47.5 height: 17.0 margin: Inset{left: 20.0 right: 0 top: 621.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "100" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 51.0 height: 17.0 margin: Inset{left: 20.0 right: 0 top: 672.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "50" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 47.5 height: 17.0 margin: Inset{left: 20.0 right: 0 top: 723.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "0" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 335.0 height: 1.0 margin: Inset{left: 20.0 right: 0 top: 688.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 335.0 height: 1.0 margin: Inset{left: 20.0 right: 0 top: 637.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 51.0 height: 17.0 margin: Inset{left: 19.0 right: 0 top: 755.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Jan" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 48.0 height: 17.0 margin: Inset{left: 332.2 right: 0 top: 755.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Jun" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 49.5 height: 17.0 margin: Inset{left: 269.5 right: 0 top: 755.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "May" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 48.5 height: 17.0 margin: Inset{left: 207.5 right: 0 top: 755.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Apr" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 50.5 height: 17.0 margin: Inset{left: 143.5 right: 0 top: 755.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Mar" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 47.5 height: 17.0 margin: Inset{left: 83.0 right: 0 top: 755.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Feb" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 370.8 height: 113.2 margin: Inset{left: 49.0 right: 0 top: 622.5 bottom: 0} draw_bg.color: #b467f3ff draw_bg.color_2: #ffffffff draw_bg.border_radius: 22.7 }
    RoundedShadowView{ width: 12.5 height: 12.5 margin: Inset{left: 211.0 right: 0 top: 636.5 bottom: 0} draw_bg.shadow_color: #24306fcd draw_bg.shadow_radius: 5.0 draw_bg.shadow_offset: vec2(0.0, 3.5) draw_bg.color: #ffffffff draw_bg.border_radius: 6.2 draw_bg.border_size: 2.0 draw_bg.border_color: #b35ff0ff }
    RoundedView{ width: 34.0 height: 20.0 margin: Inset{left: 177.0 right: 0 top: 606.5 bottom: 0} draw_bg.color: #140f2693 draw_bg.border_radius: 3.8 }
    RoundedView{ width: 6.0 height: 10.0 margin: Inset{left: 204.9 right: 0 top: 621.5 bottom: 0} draw_bg.color: #140f2693 }
    RoundedView{ width: 34.0 height: 25.0 margin: Inset{left: 177.0 right: 0 top: 606.5 bottom: 0} draw_bg.color: #140f2675 draw_bg.border_radius: 5.0 }
    RoundedView{ width: 34.0 height: 20.0 margin: Inset{left: 177.0 right: 0 top: 606.5 bottom: 0} draw_bg.color: #140f2693 draw_bg.border_radius: 3.8 }
    RoundedView{ width: 6.0 height: 10.0 margin: Inset{left: 204.9 right: 0 top: 621.5 bottom: 0} draw_bg.color: #140f2693 }
    View{ width: 52.7 height: 17.0 margin: Inset{left: 179.7 right: 0 top: 611.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "$810" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 779.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 215.5 height: 45.0 margin: Inset{left: 79.8 right: 0 top: 710.0 bottom: 0} draw_bg.color: #140f2680 draw_bg.border_radius: 22.5 }
    RoundedView{ width: 24.1 height: 24.0 margin: Inset{left: 256.1 right: 0 top: 720.5 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 135.9 height: 16.0 margin: Inset{left: 99.8 right: 0 top: 727.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Updating data. Please wait..." draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 337.4 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 220.6 height: 30.0 margin: Inset{left: 77.2 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 6.0 }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 1.4 }
    RoundedView{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 2.0 }
    RoundedView{ width: 14.0 height: 4.3 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.9 }
    RoundedView{ width: 9.1 height: 3.3 margin: Inset{left: 321.4 right: 0 top: 15.9 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.7 }
    RoundedView{ width: 4.2 height: 3.0 margin: Inset{left: 323.9 right: 0 top: 19.4 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.6 }
    RoundedView{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 1.9 }
    RoundedView{ width: 2.6 height: 3.5 margin: Inset{left: 299.0 right: 0 top: 18.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 5.2 margin: Inset{left: 303.1 right: 0 top: 17.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 7.2 margin: Inset{left: 307.2 right: 0 top: 15.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 9.2 margin: Inset{left: 311.4 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    View{ width: 67.0 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
    RoundedView{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #121217eb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 337.4 right: 0 top: 775.0 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #121217ff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
}
