// FROZEN compile of ⟶ [Stats] Transactions List — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    View{ width: 68.2 height: 16.0 margin: Inset{left: 155.9 right: 0 top: 176.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Payment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 16.9 height: 15.0 margin: Inset{left: 200.1 right: 0 top: 173.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 202.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 331.0 right: 0 top: 159.5 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 95.0 right: 0 top: 151.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 7.0 height: 7.0 margin: Inset{left: 128.5 right: 0 top: 148.0 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 3.5 }
    View{ width: 74.5 height: 17.0 margin: Inset{left: 24.0 right: 0 top: 176.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "06:34AM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 54.0 height: 28.0 margin: Inset{left: 30.5 right: 0 top: 155.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fill height: Fit text: "- $12" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 86.0 height: 21.0 margin: Inset{left: 155.0 right: 0 top: 155.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Ryan Ellis" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 68.2 height: 16.0 margin: Inset{left: 156.4 right: 0 top: 239.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Payment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 16.9 height: 15.0 margin: Inset{left: 200.6 right: 0 top: 236.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.5 right: 0 top: 265.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 331.5 right: 0 top: 222.5 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 95.5 right: 0 top: 214.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 7.0 height: 7.0 margin: Inset{left: 129.0 right: 0 top: 211.0 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.border_radius: 3.5 }
    View{ width: 74.5 height: 17.0 margin: Inset{left: 24.5 right: 0 top: 239.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "08:54PM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 54.0 height: 28.0 margin: Inset{left: 31.0 right: 0 top: 218.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fill height: Fit text: "$20" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 86.0 height: 21.0 margin: Inset{left: 155.5 right: 0 top: 218.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Max Carson" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 68.2 height: 16.0 margin: Inset{left: 156.4 right: 0 top: 302.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Payment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 16.9 height: 15.0 margin: Inset{left: 200.6 right: 0 top: 299.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.5 right: 0 top: 328.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 331.5 right: 0 top: 285.5 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 95.5 right: 0 top: 277.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 7.0 height: 7.0 margin: Inset{left: 129.0 right: 0 top: 274.0 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 3.5 }
    View{ width: 74.5 height: 17.0 margin: Inset{left: 24.5 right: 0 top: 302.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "02:25PM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 54.0 height: 28.0 margin: Inset{left: 31.0 right: 0 top: 281.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fill height: Fit text: "- $83" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 86.0 height: 21.0 margin: Inset{left: 155.5 right: 0 top: 281.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Paul Mills" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 68.2 height: 16.0 margin: Inset{left: 156.4 right: 0 top: 428.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Payment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 16.9 height: 15.0 margin: Inset{left: 200.6 right: 0 top: 425.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.5 right: 0 top: 454.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 331.5 right: 0 top: 411.5 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 95.5 right: 0 top: 403.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 7.0 height: 7.0 margin: Inset{left: 129.0 right: 0 top: 400.0 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 3.5 }
    View{ width: 74.5 height: 17.0 margin: Inset{left: 24.5 right: 0 top: 428.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "00:12AM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 54.0 height: 28.0 margin: Inset{left: 31.0 right: 0 top: 407.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fill height: Fit text: "- $3" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 86.0 height: 21.0 margin: Inset{left: 155.5 right: 0 top: 407.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Laura Burke" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 68.2 height: 16.0 margin: Inset{left: 156.4 right: 0 top: 491.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Payment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 16.9 height: 15.0 margin: Inset{left: 200.6 right: 0 top: 488.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.5 right: 0 top: 517.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 331.5 right: 0 top: 474.5 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 95.5 right: 0 top: 466.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 7.0 height: 7.0 margin: Inset{left: 129.0 right: 0 top: 463.0 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.border_radius: 3.5 }
    View{ width: 74.5 height: 17.0 margin: Inset{left: 24.5 right: 0 top: 491.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "03:40AM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 54.0 height: 28.0 margin: Inset{left: 31.0 right: 0 top: 470.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fill height: Fit text: "+ $11" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 86.0 height: 21.0 margin: Inset{left: 155.5 right: 0 top: 470.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Ian Ballard" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 68.2 height: 16.0 margin: Inset{left: 156.4 right: 0 top: 554.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Payment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 16.9 height: 15.0 margin: Inset{left: 200.6 right: 0 top: 551.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.5 right: 0 top: 580.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 331.5 right: 0 top: 537.5 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 95.5 right: 0 top: 529.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 7.0 height: 7.0 margin: Inset{left: 129.0 right: 0 top: 526.0 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.border_radius: 3.5 }
    View{ width: 74.5 height: 17.0 margin: Inset{left: 24.5 right: 0 top: 554.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "05:45PM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 54.0 height: 28.0 margin: Inset{left: 31.0 right: 0 top: 533.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fill height: Fit text: "+ $5" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 86.0 height: 21.0 margin: Inset{left: 155.5 right: 0 top: 533.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Mina Hunt" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 68.2 height: 16.0 margin: Inset{left: 156.4 right: 0 top: 617.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Payment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 16.9 height: 15.0 margin: Inset{left: 200.6 right: 0 top: 614.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.5 right: 0 top: 643.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 331.5 right: 0 top: 600.5 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 95.5 right: 0 top: 592.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 7.0 height: 7.0 margin: Inset{left: 129.0 right: 0 top: 589.0 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 3.5 }
    View{ width: 74.5 height: 17.0 margin: Inset{left: 24.5 right: 0 top: 617.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "00:28AM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 54.0 height: 28.0 margin: Inset{left: 31.0 right: 0 top: 596.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fill height: Fit text: "+ $4" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 86.0 height: 21.0 margin: Inset{left: 155.5 right: 0 top: 596.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Edna Schmidt" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 68.2 height: 16.0 margin: Inset{left: 156.4 right: 0 top: 680.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Payment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 16.9 height: 15.0 margin: Inset{left: 200.6 right: 0 top: 677.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.5 right: 0 top: 706.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 331.5 right: 0 top: 663.5 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 95.5 right: 0 top: 655.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 7.0 height: 7.0 margin: Inset{left: 129.0 right: 0 top: 652.0 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 3.5 }
    View{ width: 74.5 height: 17.0 margin: Inset{left: 24.5 right: 0 top: 680.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "05:45PM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 54.0 height: 28.0 margin: Inset{left: 31.0 right: 0 top: 659.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fill height: Fit text: "- $32" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 86.0 height: 21.0 margin: Inset{left: 155.5 right: 0 top: 659.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Mina Hunt" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 68.2 height: 16.0 margin: Inset{left: 156.4 right: 0 top: 743.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Payment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 16.9 height: 15.0 margin: Inset{left: 200.6 right: 0 top: 740.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.5 right: 0 top: 769.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 331.5 right: 0 top: 726.5 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 95.5 right: 0 top: 718.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 7.0 height: 7.0 margin: Inset{left: 129.0 right: 0 top: 715.0 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 3.5 }
    View{ width: 74.5 height: 17.0 margin: Inset{left: 24.5 right: 0 top: 743.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "00:28AM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 54.0 height: 28.0 margin: Inset{left: 31.0 right: 0 top: 722.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fill height: Fit text: "+ $3" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 86.0 height: 21.0 margin: Inset{left: 155.5 right: 0 top: 722.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Athar Malakooti" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedShadowView{ width: 375.0 height: 75.0 margin: Inset{left: 0.5 right: 0 top: 323.0 bottom: 0} draw_bg.shadow_color: #3b4a7433 draw_bg.shadow_radius: 18.0 draw_bg.shadow_offset: vec2(0.0, 3.0) draw_bg.color: #ffffffff }
    View{ width: 68.2 height: 16.0 margin: Inset{left: 156.4 right: 0 top: 365.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Payment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 16.9 height: 15.0 margin: Inset{left: 200.6 right: 0 top: 362.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 331.5 right: 0 top: 348.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 95.5 right: 0 top: 340.5 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 7.0 height: 7.0 margin: Inset{left: 129.0 right: 0 top: 337.0 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 3.5 }
    View{ width: 74.5 height: 17.0 margin: Inset{left: 24.5 right: 0 top: 365.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "09:13PM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 54.0 height: 28.0 margin: Inset{left: 31.0 right: 0 top: 344.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fill height: Fit text: "+$6" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 86.0 height: 21.0 margin: Inset{left: 155.5 right: 0 top: 344.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Travis Lloyd" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 45.0 height: 45.0 margin: Inset{left: 315.5 right: 0 top: 338.0 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 22.5 }
    RoundedView{ width: 15.4 height: 15.4 margin: Inset{left: 330.3 right: 0 top: 352.8 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 9.7 height: 9.7 margin: Inset{left: 333.2 right: 0 top: 355.7 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 139.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 55.0 height: 17.0 margin: Inset{left: 226.9 right: 0 top: 109.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "week" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 55.0 height: 17.0 margin: Inset{left: 39.5 right: 0 top: 109.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Day" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 55.0 height: 17.0 margin: Inset{left: 133.4 right: 0 top: 109.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Month" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 55.0 height: 17.0 margin: Inset{left: 320.9 right: 0 top: 109.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "all" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 119.0 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 375.0 height: 90.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 331.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 20.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 49.0 height: 20.9 margin: Inset{left: 168.0 right: 0 top: 54.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "subtitle" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 114.0 height: 18.9 margin: Inset{left: 142.5 right: 0 top: 36.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Transaction history" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    RoundedView{ width: 375.0 height: 75.0 margin: Inset{left: 0.0 right: 0 top: 737.0 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 325.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 250.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 175.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 15.5 height: 18.4 margin: Inset{left: 191.0 right: 0 top: 746.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 3.5 }
    View{ width: 21.9 height: 20.2 margin: Inset{left: 193.2 right: 0 top: 750.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "10" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 100.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 25.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 375.0 height: 1.4 margin: Inset{left: 0.0 right: 0 top: 737.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #121217eb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 337.4 right: 0 top: 775.0 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #131315eb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #121217ff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 181.0 height: 45.0 margin: Inset{left: 97.0 right: 0 top: 672.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 22.5 }
    RoundedView{ width: 20.2 height: 24.0 margin: Inset{left: 245.2 right: 0 top: 682.5 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 115.3 height: 16.0 margin: Inset{left: 113.8 right: 0 top: 689.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Fetching transactions" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 337.4 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 220.6 height: 30.0 margin: Inset{left: 77.2 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 6.0 }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 1.4 }
    RoundedView{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 2.0 }
    RoundedView{ width: 14.0 height: 4.3 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.9 }
    RoundedView{ width: 9.1 height: 3.3 margin: Inset{left: 321.4 right: 0 top: 15.9 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.7 }
    RoundedView{ width: 4.2 height: 3.0 margin: Inset{left: 323.9 right: 0 top: 19.4 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.6 }
    RoundedView{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 1.9 }
    RoundedView{ width: 2.6 height: 3.5 margin: Inset{left: 299.0 right: 0 top: 18.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 5.2 margin: Inset{left: 303.1 right: 0 top: 17.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 7.2 margin: Inset{left: 307.2 right: 0 top: 15.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 9.2 margin: Inset{left: 311.4 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    View{ width: 67.0 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
}
