// FROZEN compile of ⟶ [Stats] Data visualization #5 — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    RoundedView{ width: 375.0 height: 812.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 345.0 height: 100.0 margin: Inset{left: 15.0 right: 0 top: 472.0 bottom: 0} draw_bg.color: #00000000 draw_bg.color_2: #ffffffff draw_bg.border_radius: 10.0 }
    View{ width: 102.5 height: 32.5 margin: Inset{left: 35.0 right: 0 top: 499.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$78.39" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 35.0 height: 13.5 margin: Inset{left: 35.0 right: 0 top: 532.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 4.0 }
    View{ width: 51.0 height: 15.0 margin: Inset{left: 40.0 right: 0 top: 534.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "-12%" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 81.5 height: 15.0 margin: Inset{left: 76.0 right: 0 top: 534.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "expenses" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 345.0 height: 100.0 margin: Inset{left: 15.0 right: 0 top: 582.0 bottom: 0} draw_bg.color: #00000000 draw_bg.color_2: #ffffffff draw_bg.border_radius: 10.0 }
    View{ width: 101.5 height: 32.5 margin: Inset{left: 35.0 right: 0 top: 609.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$39.59" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 35.0 height: 13.5 margin: Inset{left: 35.0 right: 0 top: 642.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 4.0 }
    View{ width: 51.0 height: 15.0 margin: Inset{left: 40.0 right: 0 top: 644.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "+25%" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 72.5 height: 15.0 margin: Inset{left: 76.0 right: 0 top: 644.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "savings" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 375.0 height: 75.0 margin: Inset{left: 0.0 right: 0 top: 737.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 375.0 height: 1.4 margin: Inset{left: 0.0 right: 0 top: 737.0 bottom: 0} draw_bg.color: #ffffffff }
    View{ width: 49.0 height: 21.6 margin: Inset{left: 318.0 right: 0 top: 784.8 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "item label" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 325.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 49.0 height: 21.6 margin: Inset{left: 243.0 right: 0 top: 784.8 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "item label" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 250.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 49.0 height: 21.6 margin: Inset{left: 168.0 right: 0 top: 784.8 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "item label" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 175.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 15.5 height: 18.4 margin: Inset{left: 191.0 right: 0 top: 746.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 3.5 }
    View{ width: 21.9 height: 20.2 margin: Inset{left: 193.2 right: 0 top: 750.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "10" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 49.0 height: 21.6 margin: Inset{left: 93.0 right: 0 top: 784.8 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "item label" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 100.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 49.0 height: 21.6 margin: Inset{left: 18.0 right: 0 top: 784.8 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "item label" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 25.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 60.0 height: 60.0 margin: Inset{left: 157.5 right: 0 top: 727.0 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 30.0 }
    RoundedView{ width: 20.6 height: 20.6 margin: Inset{left: 177.2 right: 0 top: 746.7 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 12.8 height: 12.8 margin: Inset{left: 181.1 right: 0 top: 750.5 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 375.0 height: 90.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 331.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 20.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 49.0 height: 20.9 margin: Inset{left: 168.0 right: 0 top: 54.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "subtitle" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 53.8 height: 17.0 margin: Inset{left: 180.1 right: 0 top: 54.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "week" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 11.8 height: 15.0 margin: Inset{left: 165.2 right: 0 top: 52.0 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 53.8 height: 17.0 margin: Inset{left: 270.1 right: 0 top: 54.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "month" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 53.8 height: 17.0 margin: Inset{left: 90.0 right: 0 top: 54.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "today" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 4.0 height: 77.5 margin: Inset{left: 37.0 right: 0 top: 324.0 bottom: 0} draw_bg.color: #ffca5cff draw_bg.border_radius: 2.0 }
    View{ width: 39.0 height: 16.0 margin: Inset{left: 31.0 right: 0 top: 304.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "$2" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 56.0 height: 19.5 margin: Inset{left: 23.0 right: 0 top: 412.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "mon" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 4.0 height: 17.5 margin: Inset{left: 334.5 right: 0 top: 384.0 bottom: 0} draw_bg.color: #ff6b6fff draw_bg.border_radius: 2.0 }
    View{ width: 39.0 height: 16.0 margin: Inset{left: 328.5 right: 0 top: 364.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "$3" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 51.5 height: 19.5 margin: Inset{left: 322.8 right: 0 top: 412.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "sun" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 4.0 height: 77.5 margin: Inset{left: 285.0 right: 0 top: 324.0 bottom: 0} draw_bg.color: #987b7cff draw_bg.border_radius: 2.0 }
    View{ width: 44.5 height: 16.0 margin: Inset{left: 276.2 right: 0 top: 304.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "$16" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 48.0 height: 19.5 margin: Inset{left: 274.8 right: 0 top: 412.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "sat" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 4.0 height: 50.0 margin: Inset{left: 235.5 right: 0 top: 351.5 bottom: 0} draw_bg.color: #5fc9e9ff draw_bg.border_radius: 2.0 }
    View{ width: 48.0 height: 16.0 margin: Inset{left: 225.0 right: 0 top: 332.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "$98" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 45.5 height: 19.5 margin: Inset{left: 226.5 right: 0 top: 412.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "fri" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 4.0 height: 85.0 margin: Inset{left: 186.0 right: 0 top: 316.5 bottom: 0} draw_bg.color: #a894ffff draw_bg.border_radius: 2.0 }
    View{ width: 44.5 height: 16.0 margin: Inset{left: 177.2 right: 0 top: 297.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "$18" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 41.5 height: 19.5 margin: Inset{left: 179.0 right: 0 top: 412.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Th" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 4.0 height: 42.5 margin: Inset{left: 136.0 right: 0 top: 359.0 bottom: 0} draw_bg.color: #ff9774ff draw_bg.border_radius: 2.0 }
    View{ width: 44.5 height: 16.0 margin: Inset{left: 127.2 right: 0 top: 339.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "$18" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 56.0 height: 19.5 margin: Inset{left: 121.8 right: 0 top: 412.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "wed" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 4.0 height: 112.5 margin: Inset{left: 86.5 right: 0 top: 289.0 bottom: 0} draw_bg.color: #1ed7a6ff draw_bg.border_radius: 2.0 }
    View{ width: 47.0 height: 16.0 margin: Inset{left: 76.5 right: 0 top: 269.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "$67" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 49.5 height: 19.5 margin: Inset{left: 75.8 right: 0 top: 412.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "tue" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 242.5 height: 51.0 margin: Inset{left: 20.0 right: 0 top: 135.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$3,841.84" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 24.8 } } }
    View{ width: 129.4 height: 15.0 margin: Inset{left: 20.0 right: 0 top: 185.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "available funds" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 337.4 right: 0 top: 775.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 337.4 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 220.6 height: 30.0 margin: Inset{left: 77.2 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 6.0 }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 1.4 }
    RoundedView{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 2.0 }
    RoundedView{ width: 14.0 height: 4.3 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.9 }
    RoundedView{ width: 9.1 height: 3.3 margin: Inset{left: 321.4 right: 0 top: 15.9 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.7 }
    RoundedView{ width: 4.2 height: 3.0 margin: Inset{left: 323.9 right: 0 top: 19.4 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.6 }
    RoundedView{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 1.9 }
    RoundedView{ width: 2.6 height: 3.5 margin: Inset{left: 299.0 right: 0 top: 18.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 5.2 margin: Inset{left: 303.1 right: 0 top: 17.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 7.2 margin: Inset{left: 307.2 right: 0 top: 15.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 9.2 margin: Inset{left: 311.4 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    View{ width: 67.0 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
}
