// FROZEN compile of ⟶ [Unlock] Passcode — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    RoundedView{ width: 375.0 height: 812.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #17212dff }
    RoundedView{ width: 375.0 height: 812.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #140f2691 }
    RoundedView{ width: 80.8 height: 80.8 margin: Inset{left: 45.6 right: 0 top: 354.1 bottom: 0} draw_bg.color: #ffffff80 draw_bg.border_radius: 40.4 }
    RoundedView{ width: 20.4 height: 20.4 margin: Inset{left: 75.8 right: 0 top: 384.3 bottom: 0} draw_bg.color: #50a1ffff }
    View{ width: 48.6 height: 27.2 margin: Inset{left: 73.7 right: 0 top: 377.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "1" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 80.8 height: 80.8 margin: Inset{left: 147.1 right: 0 top: 354.1 bottom: 0} draw_bg.color: #ffffff80 draw_bg.border_radius: 40.4 }
    RoundedView{ width: 20.4 height: 20.4 margin: Inset{left: 177.3 right: 0 top: 384.3 bottom: 0} draw_bg.color: #50a1ffff }
    View{ width: 44.8 height: 15.3 margin: Inset{left: 177.3 right: 0 top: 402.1 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "abc" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 48.6 height: 27.2 margin: Inset{left: 175.2 right: 0 top: 377.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "2" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 80.8 height: 80.8 margin: Inset{left: 249.1 right: 0 top: 354.1 bottom: 0} draw_bg.color: #ffffff80 draw_bg.border_radius: 40.4 }
    RoundedView{ width: 20.4 height: 20.4 margin: Inset{left: 279.3 right: 0 top: 384.3 bottom: 0} draw_bg.color: #50a1ffff }
    View{ width: 44.8 height: 15.3 margin: Inset{left: 279.3 right: 0 top: 402.1 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "def" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 48.6 height: 27.2 margin: Inset{left: 277.2 right: 0 top: 377.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "3" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 80.8 height: 80.8 margin: Inset{left: 45.6 right: 0 top: 454.1 bottom: 0} draw_bg.color: #ffffff80 draw_bg.border_radius: 40.4 }
    RoundedView{ width: 20.4 height: 20.4 margin: Inset{left: 75.8 right: 0 top: 484.3 bottom: 0} draw_bg.color: #50a1ffff }
    View{ width: 44.8 height: 15.3 margin: Inset{left: 75.8 right: 0 top: 502.1 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "ghi" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 48.6 height: 27.2 margin: Inset{left: 73.7 right: 0 top: 477.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "4" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 80.8 height: 80.8 margin: Inset{left: 147.1 right: 0 top: 454.1 bottom: 0} draw_bg.color: #ffffff80 draw_bg.border_radius: 40.4 }
    RoundedView{ width: 20.4 height: 20.4 margin: Inset{left: 177.3 right: 0 top: 484.3 bottom: 0} draw_bg.color: #50a1ffff }
    View{ width: 44.8 height: 15.3 margin: Inset{left: 177.3 right: 0 top: 502.1 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "jkl" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 48.6 height: 27.2 margin: Inset{left: 175.2 right: 0 top: 477.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "5" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 80.8 height: 80.8 margin: Inset{left: 245.6 right: 0 top: 454.1 bottom: 0} draw_bg.color: #ffffff80 draw_bg.border_radius: 40.4 }
    RoundedView{ width: 20.4 height: 20.4 margin: Inset{left: 275.8 right: 0 top: 484.3 bottom: 0} draw_bg.color: #50a1ffff }
    View{ width: 44.8 height: 15.3 margin: Inset{left: 275.8 right: 0 top: 502.1 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "mno" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 48.6 height: 27.2 margin: Inset{left: 273.7 right: 0 top: 477.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "6" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 80.8 height: 80.8 margin: Inset{left: 49.1 right: 0 top: 554.1 bottom: 0} draw_bg.color: #ffffff80 draw_bg.border_radius: 40.4 }
    RoundedView{ width: 20.4 height: 20.4 margin: Inset{left: 79.3 right: 0 top: 584.3 bottom: 0} draw_bg.color: #50a1ffff }
    View{ width: 44.8 height: 15.3 margin: Inset{left: 79.3 right: 0 top: 602.1 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "pqrs" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 48.6 height: 27.2 margin: Inset{left: 77.2 right: 0 top: 577.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "7" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 80.8 height: 80.8 margin: Inset{left: 147.1 right: 0 top: 554.1 bottom: 0} draw_bg.color: #ffffff80 draw_bg.border_radius: 40.4 }
    RoundedView{ width: 20.4 height: 20.4 margin: Inset{left: 177.3 right: 0 top: 584.3 bottom: 0} draw_bg.color: #50a1ffff }
    View{ width: 44.8 height: 15.3 margin: Inset{left: 177.3 right: 0 top: 602.1 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "tuv" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 48.6 height: 27.2 margin: Inset{left: 175.2 right: 0 top: 577.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "8" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 80.8 height: 80.8 margin: Inset{left: 245.6 right: 0 top: 554.1 bottom: 0} draw_bg.color: #ffffff80 draw_bg.border_radius: 40.4 }
    RoundedView{ width: 20.4 height: 20.4 margin: Inset{left: 275.8 right: 0 top: 584.3 bottom: 0} draw_bg.color: #50a1ffff }
    View{ width: 44.8 height: 15.3 margin: Inset{left: 275.8 right: 0 top: 602.1 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "wxyz" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 48.6 height: 27.2 margin: Inset{left: 273.7 right: 0 top: 577.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "9" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 80.8 height: 80.8 margin: Inset{left: 147.1 right: 0 top: 654.1 bottom: 0} draw_bg.color: #ffffff80 draw_bg.border_radius: 40.4 }
    RoundedView{ width: 20.4 height: 20.4 margin: Inset{left: 177.3 right: 0 top: 684.3 bottom: 0} draw_bg.color: #50a1ffff }
    View{ width: 48.6 height: 27.2 margin: Inset{left: 175.2 right: 0 top: 677.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "0" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 80.8 height: 80.8 margin: Inset{left: 49.1 right: 0 top: 654.1 bottom: 0} draw_bg.color: #ffffff80 draw_bg.border_radius: 40.4 }
    RoundedView{ width: 20.4 height: 20.4 margin: Inset{left: 79.3 right: 0 top: 684.3 bottom: 0} draw_bg.color: #1c8ff856 }
    RoundedView{ width: 80.8 height: 80.8 margin: Inset{left: 245.6 right: 0 top: 654.1 bottom: 0} draw_bg.color: #ffffff80 draw_bg.border_radius: 40.4 }
    RoundedView{ width: 20.4 height: 20.4 margin: Inset{left: 275.8 right: 0 top: 684.3 bottom: 0} draw_bg.color: #1c8ff856 }
    View{ width: 170.5 height: 48.0 margin: Inset{left: 107.2 right: 0 top: 154.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "Login with Touch ID or Passcode" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 84.0 right: 0 top: 267.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 7.5 }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 199.0 right: 0 top: 267.0 bottom: 0} draw_bg.color: #ffffff4f draw_bg.border_radius: 7.5 draw_bg.border_size: 1.5 draw_bg.border_color: #ffffff42 }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 237.5 right: 0 top: 267.0 bottom: 0} draw_bg.color: #ffffff4f draw_bg.border_radius: 7.5 draw_bg.border_size: 1.5 draw_bg.border_color: #ffffff42 }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 276.0 right: 0 top: 267.0 bottom: 0} draw_bg.color: #ffffff4f draw_bg.border_radius: 7.5 draw_bg.border_size: 1.5 draw_bg.border_color: #ffffff42 }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 160.5 right: 0 top: 267.0 bottom: 0} draw_bg.color: #ffffff4f draw_bg.border_radius: 7.5 draw_bg.border_size: 1.5 draw_bg.border_color: #ffffff42 }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 122.5 right: 0 top: 267.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 7.5 }
    RoundedView{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 337.4 right: 0 top: 775.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 37.5 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.4 }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ffff }
    RoundedView{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 337.4 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 37.5 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 7.5 }
    RoundedView{ width: 220.6 height: 30.0 margin: Inset{left: 77.2 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 6.0 }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.2 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 1.4 }
    RoundedView{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 2.0 }
    RoundedView{ width: 14.0 height: 4.3 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.9 }
    RoundedView{ width: 9.1 height: 3.3 margin: Inset{left: 321.4 right: 0 top: 15.9 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.7 }
    RoundedView{ width: 4.2 height: 3.0 margin: Inset{left: 323.9 right: 0 top: 19.4 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.6 }
    RoundedView{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 1.9 }
    RoundedView{ width: 2.6 height: 3.5 margin: Inset{left: 299.0 right: 0 top: 18.8 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 5.2 margin: Inset{left: 303.1 right: 0 top: 17.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 7.2 margin: Inset{left: 307.2 right: 0 top: 15.1 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    RoundedView{ width: 2.6 height: 9.2 margin: Inset{left: 311.4 right: 0 top: 13.0 bottom: 0} draw_bg.color: #ffffffeb draw_bg.border_radius: 0.5 }
    View{ width: 67.0 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
}
