#!/usr/bin/env python3
"""Generate the accent axis as a palette knob rather than a widget tint.

The axis shipped setting five tokens — `l0_accent` (which nothing reads),
`l0_bar`, `l0_active`, `l0_go`, `l0_bar_rail`. That reaches a temperature bar, a
selected chip and one button, so a stock card showed no accent at all and every
"do palettes help?" measurement was really asking "does tinting three widgets
help?".

What a palette actually carries is its GROUND and its INK. The ground belongs to
the mood — `theme dark` and `theme light` differ by exactly that — so the accent
takes the INK: `l0_text` and the two inks derived from it. An Art Deco restyle
that reads as gold-on-teal is teal ground (mood) plus gold ink (accent), and
those are two independent choices that have to compose.

The kit language has no colour math — every value is an `argb(...)` literal — so
a delta cannot compute a tint from whatever ground the mood happens to set. It
has to be the cross product, generated: mood x hue, with contrast solved per
pair. That is what this writes.

Contrast is held against the PANEL, not the page. `l0_fill` is usually white at
low alpha over the base, so the panel is the lighter surface and the binding
constraint; solving on the page alone is how `l0_dim` shipped at 2.48:1.

Usage:  gen_accent_axes.py [--check]
"""
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from e4_roundtrip import (  # noqa: E402
    DIM_MAX, SOFT_MAX, contrast, mix, over, rel_lum, step_back,
)

L0 = HERE.parent.parent / "splash-makepad" / "components" / "l0"
MOODS = ["dark", "light", "glass", "photo", "vibrant", "minimal",
         # theme packs answer every hue too — a pack is a mood with luggage
         "atro", "atro_light",
         "camo", "camo_light"]
# The hues the axis already named, unchanged — this is a rewiring, not a
# repalette. Keeping them identical means any measured difference is the
# wiring and not a new set of colours.
HUES = {
    "indigo":  (109, 121, 240),
    "blue":    (26, 115, 232),
    "red":     (224, 46, 36),
    "green":   (30, 142, 90),
    "amber":   (245, 166, 35),
    "cyan":    (18, 181, 201),
    "magenta": (214, 64, 159),
    "violet":  (139, 92, 246),
}
FLOOR = 4.5

ARGB = re.compile(r"^let\s+(\w+)\s*=\s*argb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)")


def tokens(path):
    """Every `let <name> = argb(a,r,g,b)` in a palette file, last binding wins."""
    out = {}
    for line in path.read_text().splitlines():
        m = ARGB.match(line.strip())
        if m:
            out[m.group(1)] = tuple(int(g) for g in m.groups()[1:])
    return out


def mood_surfaces(mood):
    """The opaque page and the composited panel this mood actually paints.

    `l0_fill` is an ALPHA over the base in four of six moods, so the panel is
    not the token's own colour — compositing it is the difference between
    solving against #ffffff12 (meaningless) and against the near-black it
    actually produces.
    """
    t = tokens(L0 / "_palette_dark.splash")
    if mood != "dark":
        t.update(tokens(L0 / f"_palette_{mood}.splash"))
    ba, br, bg, bb = t["l0_base"]
    ground = over(ba, (br, bg, bb), (0, 0, 0)) if ba < 255 else (br, bg, bb)
    fa, fr, fg, fb = t["l0_fill"]
    panel = over(fa, (fr, fg, fb), ground)
    ia, ir, ig, ib = t["l0_text"]
    return ground, panel, (ir, ig, ib)


def tint(ink, hue, ground, panel, floor=FLOOR):
    """The strongest pull toward the hue that both surfaces still carry.

    Walks DOWN from the full hue rather than up from the ink, because the
    interesting answer is the most saturated one that works — an accent that
    only ever tints 5% is the widget-knob failure in a new costume. Returns the
    fraction alongside the colour so the emitted file can state honestly how
    much of the hue survived.
    """
    for k in range(20, 0, -1):
        t = k / 20
        c = mix(ink, hue, t)
        if contrast(c, ground) >= floor and contrast(c, panel) >= floor:
            return c, t
    return ink, 0.0


def hx(c):
    return f"argb(255, {c[0]:3d}, {c[1]:3d}, {c[2]:3d})"


def build(mood, name, hue):
    ground, panel, ink = mood_surfaces(mood)
    text, t = tint(ink, hue, ground, panel)
    soft = step_back(text, panel, SOFT_MAX)
    dim = step_back(text, panel, DIM_MAX)
    # The accent used as a FILL still has to be seen, but it is not body text —
    # 3:1 is the large-text/graphical bar, which is what a bar and a chip are.
    fill_ok = contrast(hue, panel) >= 3.0
    worst = min(contrast(text, ground), contrast(text, panel),
                contrast(soft, panel), contrast(dim, panel))
    head = [
        f"// Axis delta: accent .{name} over `{mood}` — generated by "
        "lab/gates/gen_accent_axes.py.",
        "//",
        "// The hue reaches the INK, which is what a palette is; the ground stays",
        f"// the mood's. Tint {t*100:.0f}% toward the hue — the strongest pull that",
        f"// still clears {FLOOR}:1 on BOTH the page and the composited panel.",
        f"// Worst pair {worst:.2f}:1"
        + ("" if fill_ok else "  ·  bar/chip fill below 3:1 on this mood"),
    ]
    if t == 0.0:
        head.append("// NOTE: this hue cannot carry body text on this ground at "
                    "any strength;")
        head.append("//       the ink is left alone rather than silently "
                    "inverted.")
    body = [
        "",
        f"let l0_text     = {hx(text)}",
        f"let l0_soft     = {hx(soft)}",
        f"let l0_dim      = {hx(dim)}",
        "",
        f"let l0_accent   = {hx(hue)}",
        "let l0_bar      = l0_accent",
        f"let l0_bar_rail = argb( 38, 128, 128, 128)",
        f"let l0_active   = argb( 72, {hue[0]}, {hue[1]}, {hue[2]})",
        "let l0_go       = l0_accent",
        "",
        "// accent-as-seed: with a seeded ground, _derive_color re-solves the",
        "// ink against THAT ground in-kit (unrolled five-step contrast search)",
        "// instead of keeping this fragment's mood-solved literals.",
        "let seed_hue_on = 1",
        f"let seed_hue_r  = {hue[0]}",
        f"let seed_hue_g  = {hue[1]}",
        f"let seed_hue_b  = {hue[2]}",
        "",
    ]
    return "\n".join(head + body), worst, t


def main():
    check = "--check" in sys.argv
    rows, wrote = [], 0
    for mood in MOODS:
        for name, hue in sorted(HUES.items()):
            src, worst, t = build(mood, name, hue)
            dst = L0 / f"_axis_accent_{name}_{mood}.splash"
            if not check:
                dst.write_text(src)
                wrote += 1
            rows.append((mood, name, t, worst))
    # `neutral` is the identity: the mood's own ink, untouched.
    if not check:
        (L0 / "_axis_accent_neutral.splash").write_text(
            "// Axis delta: accent .neutral — the identity. The mood's own ink,\n"
            "// untouched, so a card that names no accent and one that names\n"
            "// `.neutral` render identically.\n")

    print(f"{wrote} fragments -> {L0}\n")
    print(f"{'mood':<9} {'hue':<9} {'tint':>5}  {'worst':>6}")
    for mood, name, t, worst in rows:
        flag = "  <- ink unmoved" if t == 0.0 else ("  <- below AA" if worst < FLOOR else "")
        print(f"{mood:<9} {name:<9} {t*100:4.0f}%  {worst:5.2f}:1{flag}")
    dead = [r for r in rows if r[2] == 0.0]
    below = [r for r in rows if r[3] < FLOOR]
    print(f"\n{len(rows)} pairs · {len(dead)} cannot carry the hue at all · "
          f"{len(below)} below {FLOOR}:1")


if __name__ == "__main__":
    main()
