#!/usr/bin/env python3
"""Gradients as FORMULAS, derived from the palette — never as generated images.

An image cannot rescale to an unknown viewport, cannot recolour when the card
names an accent, and cannot follow a mood. A gradient is two colours and a
direction, so it should be computed from the palette that is already solved. The
asset generator deliberately does not make these; this does.

What the renderer actually supports, read off `l0_widgets.rs`: a TWO-STOP
VERTICAL gradient on any node that sets `bg` and `bg2`, mixed down `pos.y` and
dithered. Not an angle, not a third stop, not a radial. So every family here is
expressible today — which is the point of deriving them rather than inventing a
vocabulary the renderer would refuse.

The one rule they all obey: the far stop must move AWAY from the panel's fill.
A page gradient that ends on the panel's own colour has separation zero, and the
card dissolves into the page at the bottom of the screen — measured on the light
mood, where a judge called the result "near-white, flat low-contrast surfaces".
`separation()` is that check, and it is worth running on the shipped palettes
too rather than only on new ones.

Usage:  gradients.py [--audit]        audit the shipped moods
        gradients.py --mood dark --family accent_wash --accent amber
"""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from e4_roundtrip import contrast, mix, over, rel_lum  # noqa: E402
from gen_accent_axes import HUES, MOODS, mood_surfaces, hx  # noqa: E402

# How far apart the bottom stop and the panel have to stay. The shipped dark
# mood measures 1.09:1 and reads fine because its panel is a LIGHTER film over
# the page; the failure mode is the light mood's, where the page lifted to the
# panel's exact white. 1.06 is below the dark mood's own number, so this rejects
# the merge without failing a look that already ships.
MERGE_FLOOR = 1.06

# `photo` is exempt, and not as a convenience. Its page IS a photograph — the
# palette's own comment says `l0_base` exists "for the strip a photo misses" —
# so the panel sits over the picture and never over `l0_base` at all. Measuring
# their separation compares two colours that are never adjacent on screen, and
# the first run of this audit duly reported four merges on `photo` and none of
# them was real. Legibility over a photograph is the scrim's job, which
# `scrim_top_alpha` already solves against the worst-case image.
PHOTO_EXEMPT = {"photo"}


def separation(base2, panel):
    """How well the far stop stays off the panel it sits behind."""
    return contrast(base2, panel)


def _away(ground, panel, amount):
    """Push the ground AWAY from the panel, by luminance, not by a fixed hue."""
    dest = (0, 0, 0) if rel_lum(panel) > rel_lum(ground) else (255, 255, 255)
    return mix(ground, dest, amount)


def family(name, ground, panel, accent=None):
    """One named gradient, as the (top, bottom) pair the kit binds."""
    if name == "flat":
        return ground, ground
    if name == "fall":
        return ground, _away(ground, panel, 0.06)
    if name == "deepen":
        return ground, _away(ground, panel, 0.18)
    if name == "rise":
        # Toward the panel — legible only while it stays off it, so it is the
        # family most likely to be refused, and it should be.
        return ground, mix(ground, panel, 0.30)
    if name == "accent_wash":
        if accent is None:
            return None
        return ground, mix(ground, accent, 0.22)
    raise KeyError(name)


FAMILIES = ["flat", "fall", "deepen", "rise", "accent_wash"]


def emit(mood, name, accent_name=None):
    ground, panel, _ = mood_surfaces(mood)
    accent = HUES.get(accent_name) if accent_name else None
    pair = family(name, ground, panel, accent)
    if pair is None:
        return None, 0.0
    top, bot = pair
    sep = separation(bot, panel)
    tag = f"{name}" + (f" .{accent_name}" if accent_name else "")
    src = "\n".join([
        f"// Gradient: {tag} over `{mood}` — a two-stop vertical fill, the only",
        "// kind this renderer draws. Generated by lab/gates/gradients.py.",
        f"// Bottom stop sits {sep:.2f}:1 off the panel"
        + ("" if sep >= MERGE_FLOOR else "  <- MERGES, the card dissolves at the foot"),
        "",
        f"let l0_base     = {hx(top)}",
        f"let l0_base_2   = {hx(bot)}",
        "",
    ])
    return src, sep


def audit():
    """Every mood x family, and whether the far stop clears the panel."""
    print(f"{'mood':<9} {'family':<13} {'separation':>11}")
    bad = 0
    for mood in MOODS:
        ground, panel, _ = mood_surfaces(mood)
        for name in FAMILIES:
            accents = [None] if name != "accent_wash" else ["amber", "blue"]
            for a in accents:
                _, sep = emit(mood, name, a)
                tag = name + (f":{a}" if a else "")
                if mood in PHOTO_EXEMPT:
                    print(f"{mood:<9} {tag:<13} {sep:>8.2f}:1  (n/a — page is a photo)")
                    continue
                flag = "" if sep >= MERGE_FLOOR else "  <- merges"
                bad += 0 if sep >= MERGE_FLOOR else 1
                print(f"{mood:<9} {tag:<13} {sep:>8.2f}:1{flag}")
    print(f"\n{bad} combinations merge into the panel and must not ship.")

    # And the shipped values, which is the check that matters: a formula that
    # passes while the incumbent fails would mean the floor is wrong.
    print(f"\nshipped, for comparison (floor {MERGE_FLOOR}):")
    from gen_accent_axes import tokens, L0
    for mood in MOODS:
        t = tokens(L0 / "_palette_dark.splash")
        if mood != "dark":
            t.update(tokens(L0 / f"_palette_{mood}.splash"))
        ground, panel, _ = mood_surfaces(mood)
        if "l0_base_2" not in t:
            print(f"  {mood:<9} no l0_base_2 — flat page")
            continue
        a, r, g, b = t["l0_base_2"]
        bot = over(a, (r, g, b), ground) if a < 255 else (r, g, b)
        sep = separation(bot, panel)
        note = ("  (n/a — page is a photo)" if mood in PHOTO_EXEMPT
                else "" if sep >= MERGE_FLOOR else "  <- MERGES")
        print(f"  {mood:<9} {sep:.2f}:1{note}")


def main():
    if "--audit" in sys.argv or len(sys.argv) == 1:
        return audit()
    mood = sys.argv[sys.argv.index("--mood") + 1]
    name = sys.argv[sys.argv.index("--family") + 1]
    accent = sys.argv[sys.argv.index("--accent") + 1] if "--accent" in sys.argv else None
    src, _ = emit(mood, name, accent)
    print(src)


if __name__ == "__main__":
    main()
