// FROZEN compile of ⟶ [Account] Phone Validation — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    RoundedView{ width: 375.0 height: 812.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 124.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 587.8 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 65.0 height: 1.0 margin: Inset{left: 92.0 right: 0 top: 554.9 bottom: 0} draw_bg.color: #ffffff0e }
    View{ width: 21.7 height: 30.9 margin: Inset{left: 54.2 right: 0 top: 535.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "1" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 124.0 height: 1.0 margin: Inset{left: 125.0 right: 0 top: 587.8 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 65.0 height: 1.0 margin: Inset{left: 217.0 right: 0 top: 554.9 bottom: 0} draw_bg.color: #ffffff0e }
    View{ width: 27.0 height: 16.9 margin: Inset{left: 175.5 right: 0 top: 564.4 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "abc" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 21.7 height: 30.9 margin: Inset{left: 179.2 right: 0 top: 535.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "2" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 124.0 height: 1.0 margin: Inset{left: 250.0 right: 0 top: 587.8 bottom: 0} draw_bg.color: #ffffff0e }
    View{ width: 27.0 height: 16.9 margin: Inset{left: 300.5 right: 0 top: 564.4 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "def" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 21.7 height: 30.9 margin: Inset{left: 304.2 right: 0 top: 535.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "3" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 124.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 652.5 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 65.0 height: 1.0 margin: Inset{left: 92.0 right: 0 top: 619.6 bottom: 0} draw_bg.color: #ffffff0e }
    View{ width: 27.0 height: 16.9 margin: Inset{left: 50.5 right: 0 top: 629.1 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "ghi" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 21.7 height: 30.9 margin: Inset{left: 54.2 right: 0 top: 600.2 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "4" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 124.0 height: 1.0 margin: Inset{left: 125.0 right: 0 top: 652.5 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 65.0 height: 1.0 margin: Inset{left: 217.0 right: 0 top: 619.6 bottom: 0} draw_bg.color: #ffffff0e }
    View{ width: 27.0 height: 16.9 margin: Inset{left: 175.5 right: 0 top: 629.1 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "jkl" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 21.7 height: 30.9 margin: Inset{left: 179.2 right: 0 top: 600.2 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "5" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 124.0 height: 1.0 margin: Inset{left: 250.0 right: 0 top: 652.5 bottom: 0} draw_bg.color: #ffffff0e }
    View{ width: 27.0 height: 16.9 margin: Inset{left: 300.5 right: 0 top: 629.1 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "mno" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 21.7 height: 30.9 margin: Inset{left: 304.2 right: 0 top: 600.2 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "6" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 124.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 717.2 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 65.0 height: 1.0 margin: Inset{left: 92.0 right: 0 top: 684.4 bottom: 0} draw_bg.color: #ffffff0e }
    View{ width: 28.5 height: 16.9 margin: Inset{left: 50.5 right: 0 top: 693.9 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "pqrs" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 21.7 height: 30.9 margin: Inset{left: 54.2 right: 0 top: 665.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "7" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 124.0 height: 1.0 margin: Inset{left: 125.0 right: 0 top: 717.2 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 65.0 height: 1.0 margin: Inset{left: 217.0 right: 0 top: 684.4 bottom: 0} draw_bg.color: #ffffff0e }
    View{ width: 27.0 height: 16.9 margin: Inset{left: 175.5 right: 0 top: 693.9 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "tuv" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 21.7 height: 30.9 margin: Inset{left: 179.2 right: 0 top: 665.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "8" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 124.0 height: 1.0 margin: Inset{left: 250.0 right: 0 top: 717.2 bottom: 0} draw_bg.color: #ffffff0e }
    View{ width: 28.5 height: 16.9 margin: Inset{left: 300.5 right: 0 top: 693.9 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "wxyz" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 21.7 height: 30.9 margin: Inset{left: 304.2 right: 0 top: 665.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "9" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 124.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 782.0 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 65.0 height: 1.0 margin: Inset{left: 92.0 right: 0 top: 749.1 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 24.0 height: 23.9 margin: Inset{left: 50.5 right: 0 top: 737.6 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 12.5 height: 6.0 margin: Inset{left: 56.5 right: 0 top: 746.6 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/9acd59ca5078c211.png") }
    RoundedView{ width: 124.0 height: 1.0 margin: Inset{left: 125.0 right: 0 top: 782.0 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 65.0 height: 1.0 margin: Inset{left: 217.0 right: 0 top: 749.1 bottom: 0} draw_bg.color: #ffffff0e }
    View{ width: 21.7 height: 30.9 margin: Inset{left: 179.2 right: 0 top: 729.7 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "0" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    RoundedView{ width: 24.0 height: 23.9 margin: Inset{left: 300.5 right: 0 top: 737.6 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 17.5 height: 12.4 margin: Inset{left: 304.0 right: 0 top: 743.6 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/16b5ec12c161b14c.png") }
    Image{ width: 4.8 height: 4.7 margin: Inset{left: 312.8 right: 0 top: 747.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/02c174022093707a.png") }
    Image{ width: 4.8 height: 4.7 margin: Inset{left: 312.8 right: 0 top: 747.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/7da133a0fa8f7db1.png") }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 522.0 bottom: 0} draw_bg.color: #ffffff0e }
    View{ width: 229.0 height: 16.0 margin: Inset{left: 87.5 right: 0 top: 474.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Resend confirmation code (1:17)" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    View{ width: 272.0 height: 48.0 margin: Inset{left: 57.0 right: 0 top: 166.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fill height: Fit text: "A 6-digit confirmation code has been sent to 810-089-5940 via SMS." draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 line_spacing: 2.0 } } }
    RoundedView{ width: 375.0 height: 90.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 20.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 4.7 height: 12.2 margin: Inset{left: 26.0 right: 0 top: 45.6 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/5a2d601a49d66b9c.png") }
    View{ width: 119.2 height: 18.9 margin: Inset{left: 142.5 right: 0 top: 36.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Validate number" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    RoundedView{ width: 45.0 height: 60.0 margin: Inset{left: 40.0 right: 0 top: 242.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 5.0 }
    View{ width: 25.1 height: 41.0 margin: Inset{left: 56.0 right: 0 top: 254.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "1" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 18.6 } } }
    RoundedView{ width: 45.0 height: 60.0 margin: Inset{left: 90.0 right: 0 top: 242.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 5.0 }
    View{ width: 25.1 height: 41.0 margin: Inset{left: 102.8 right: 0 top: 254.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "3" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 18.6 } } }
    RoundedView{ width: 45.0 height: 60.0 margin: Inset{left: 140.0 right: 0 top: 242.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 5.0 }
    View{ width: 25.1 height: 41.0 margin: Inset{left: 152.0 right: 0 top: 254.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "6" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 18.6 } } }
    RoundedView{ width: 41.0 height: 56.0 margin: Inset{left: 192.0 right: 0 top: 244.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 5.0 }
    RoundedView{ width: 45.0 height: 60.0 margin: Inset{left: 240.0 right: 0 top: 242.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 5.0 }
    View{ width: 25.1 height: 41.0 margin: Inset{left: 202.8 right: 0 top: 254.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "2" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 18.6 } } }
    RoundedView{ width: 45.0 height: 60.0 margin: Inset{left: 290.0 right: 0 top: 242.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 5.0 }
    Image{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/d5c153885dd141a3.png") }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    Image{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/dbbd9db129e5adec.png") }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #ffffff66 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 1.4 }
    Image{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/f9e85dd1496baadf.png") }
    Image{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/47adc1dc07e11640.png") }
    View{ width: 55.9 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
}
