// FROZEN compile of ⟶ [Calendar] View #6 — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    RoundedView{ width: 46.5 height: 667.0 margin: Inset{left: 0.0 right: 0 top: 145.0 bottom: 0} draw_bg.color: #ffffff33 }
    RoundedView{ width: 46.5 height: 667.0 margin: Inset{left: 46.5 right: 0 top: 145.0 bottom: 0} draw_bg.color: #ffffff33 }
    RoundedView{ width: 46.5 height: 667.0 margin: Inset{left: 93.5 right: 0 top: 145.0 bottom: 0} draw_bg.color: #ffffff33 }
    RoundedView{ width: 46.5 height: 667.0 margin: Inset{left: 140.5 right: 0 top: 145.0 bottom: 0} draw_bg.color: #ffffff33 }
    RoundedView{ width: 46.5 height: 667.0 margin: Inset{left: 187.5 right: 0 top: 145.0 bottom: 0} draw_bg.color: #ffffff33 }
    RoundedView{ width: 46.5 height: 667.0 margin: Inset{left: 234.5 right: 0 top: 145.0 bottom: 0} draw_bg.color: #ffffff33 }
    RoundedView{ width: 46.5 height: 667.0 margin: Inset{left: 281.5 right: 0 top: 145.0 bottom: 0} draw_bg.color: #ffffff33 }
    RoundedView{ width: 46.5 height: 667.0 margin: Inset{left: 328.5 right: 0 top: 145.0 bottom: 0} draw_bg.color: #ffffff33 }
    RoundedView{ width: 670.0 height: 1.0 margin: Inset{left: -289.5 right: 0 top: 479.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 670.0 height: 1.0 margin: Inset{left: -242.5 right: 0 top: 480.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 670.0 height: 1.0 margin: Inset{left: -195.5 right: 0 top: 480.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 670.0 height: 1.0 margin: Inset{left: -148.5 right: 0 top: 480.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 670.0 height: 1.0 margin: Inset{left: -101.5 right: 0 top: 480.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 670.0 height: 1.0 margin: Inset{left: -54.5 right: 0 top: 480.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 670.0 height: 1.0 margin: Inset{left: -7.5 right: 0 top: 480.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 330.0 height: 1.0 margin: Inset{left: 46.0 right: 0 top: 175.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 31.4 height: 15.5 margin: Inset{left: 8.5 right: 0 top: 172.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "06:00" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 330.0 height: 1.0 margin: Inset{left: 46.0 right: 0 top: 236.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 30.8 height: 15.5 margin: Inset{left: 9.0 right: 0 top: 232.5 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "07:00" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 330.0 height: 1.0 margin: Inset{left: 46.0 right: 0 top: 297.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 31.9 height: 15.5 margin: Inset{left: 8.0 right: 0 top: 293.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "08:00" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 330.0 height: 1.0 margin: Inset{left: 46.0 right: 0 top: 358.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 31.4 height: 15.5 margin: Inset{left: 8.5 right: 0 top: 354.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "09:00" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 330.0 height: 1.0 margin: Inset{left: 46.0 right: 0 top: 419.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 30.8 height: 15.5 margin: Inset{left: 10.5 right: 0 top: 415.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "10:00" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 330.0 height: 1.0 margin: Inset{left: 46.0 right: 0 top: 480.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 30.8 height: 15.5 margin: Inset{left: 13.0 right: 0 top: 476.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "11:00" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 330.0 height: 1.0 margin: Inset{left: 46.0 right: 0 top: 541.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 30.8 height: 15.5 margin: Inset{left: 11.0 right: 0 top: 537.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "12:00" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 330.0 height: 1.0 margin: Inset{left: 46.0 right: 0 top: 602.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 30.8 height: 15.5 margin: Inset{left: 11.0 right: 0 top: 598.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "13:00" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 330.0 height: 1.0 margin: Inset{left: 46.0 right: 0 top: 663.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 30.8 height: 15.5 margin: Inset{left: 10.5 right: 0 top: 659.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "14:00" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 330.0 height: 1.0 margin: Inset{left: 46.0 right: 0 top: 724.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 30.8 height: 15.5 margin: Inset{left: 11.0 right: 0 top: 720.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "15:00" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 187.5 height: 60.0 margin: Inset{left: 45.5 right: 0 top: 237.5 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 4.8 }
    RoundedView{ width: 187.5 height: 60.0 margin: Inset{left: 45.5 right: 0 top: 237.5 bottom: 0} draw_bg.color: #d8d8d824 draw_bg.border_radius: 4.8 }
    RoundedView{ width: 281.5 height: 60.0 margin: Inset{left: 45.5 right: 0 top: 603.5 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 7.3 }
    RoundedView{ width: 281.5 height: 60.0 margin: Inset{left: 45.5 right: 0 top: 603.5 bottom: 0} draw_bg.color: #d8d8d824 draw_bg.border_radius: 7.3 }
    RoundedView{ width: 46.0 height: 53.5 margin: Inset{left: 93.0 right: 0 top: 194.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 7.5 }
    View{ width: 46.0 height: 51.5 margin: Inset{left: 98.0 right: 0 top: 199.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "It’s A Design Event!" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 line_spacing: 2.0 } } }
    RoundedView{ width: 46.0 height: 68.5 margin: Inset{left: 187.0 right: 0 top: 298.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 7.5 }
    View{ width: 46.0 height: 63.7 margin: Inset{left: 192.0 right: 0 top: 304.9 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "The Design Design" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 line_spacing: 2.0 } } }
    RoundedView{ width: 46.0 height: 53.5 margin: Inset{left: 187.0 right: 0 top: 400.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 7.5 }
    View{ width: 46.0 height: 51.5 margin: Inset{left: 192.0 right: 0 top: 405.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "Peak Design" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 line_spacing: 2.0 } } }
    RoundedView{ width: 46.0 height: 105.0 margin: Inset{left: 140.0 right: 0 top: 497.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 7.5 }
    View{ width: 46.0 height: 93.3 margin: Inset{left: 145.0 right: 0 top: 506.8 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "The Past, Current, and Future of Design" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 line_spacing: 2.0 } } }
    RoundedView{ width: 46.0 height: 68.5 margin: Inset{left: 93.0 right: 0 top: 608.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 7.5 }
    View{ width: 46.0 height: 63.7 margin: Inset{left: 98.0 right: 0 top: 614.9 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "Leadership in Design" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 line_spacing: 2.0 } } }
    RoundedView{ width: 46.0 height: 181.0 margin: Inset{left: 234.0 right: 0 top: 481.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 7.5 }
    View{ width: 46.0 height: 155.2 margin: Inset{left: 239.0 right: 0 top: 498.4 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "7th Annual Design Workshop" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 line_spacing: 2.0 } } }
    RoundedView{ width: 46.0 height: 60.0 margin: Inset{left: 281.0 right: 0 top: 237.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 7.5 }
    View{ width: 46.0 height: 56.8 margin: Inset{left: 286.0 right: 0 top: 243.1 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "Design:Behind The Sce…" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 line_spacing: 2.0 } } }
    RoundedView{ width: 46.0 height: 85.0 margin: Inset{left: 281.0 right: 0 top: 376.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 7.5 }
    View{ width: 46.0 height: 77.1 margin: Inset{left: 286.0 right: 0 top: 383.9 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "Design Hackathon" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 line_spacing: 2.0 } } }
    RoundedView{ width: 46.0 height: 168.5 margin: Inset{left: 93.0 right: 0 top: 316.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 7.5 }
    View{ width: 46.0 height: 145.0 margin: Inset{left: 98.0 right: 0 top: 331.8 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "A Traditional Evening of Design" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 line_spacing: 2.0 } } }
    Image{ width: 57.2 height: 16.0 margin: Inset{left: 10.0 right: 0 top: 436.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/f3c62ef7a5c72b0b.png") }
    RoundedView{ width: 307.8 height: 2.0 margin: Inset{left: 67.2 right: 0 top: 443.5 bottom: 0} draw_bg.color: #d8d8d8ff }
    Image{ width: 365.0 height: 16.0 margin: Inset{left: 10.0 right: 0 top: 436.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/7bc6406acc85f258.png") }
    View{ width: 30.8 height: 15.5 margin: Inset{left: 14.3 right: 0 top: 439.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "10:21" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedShadowView{ width: 375.0 height: 55.0 margin: Inset{left: 0.0 right: 0 top: 90.0 bottom: 0} draw_bg.shadow_color: #3b4a7433 draw_bg.shadow_radius: 34.5 draw_bg.shadow_offset: vec2(0.0, 10.0) draw_bg.color: #ffffffff draw_bg.border_radius: 10.0 }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 15.5 right: 0 top: 110.0 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 9.5 height: 7.1 margin: Inset{left: 18.5 right: 0 top: 113.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/0fb45914793dec5d.png") }
    View{ width: 27.0 height: 15.5 margin: Inset{left: 58.2 right: 0 top: 102.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "mon" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    View{ width: 26.3 height: 26.0 margin: Inset{left: 63.8 right: 0 top: 112.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "11" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 22.0 height: 15.5 margin: Inset{left: 107.0 right: 0 top: 102.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "tue" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    View{ width: 26.3 height: 26.0 margin: Inset{left: 109.2 right: 0 top: 111.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "12" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 27.0 height: 15.5 margin: Inset{left: 152.2 right: 0 top: 102.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "wed" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    View{ width: 26.3 height: 26.0 margin: Inset{left: 156.2 right: 0 top: 111.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "13" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 23.1 height: 15.5 margin: Inset{left: 201.0 right: 0 top: 102.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "thu" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    View{ width: 26.3 height: 26.0 margin: Inset{left: 202.5 right: 0 top: 111.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "14" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 21.7 height: 15.5 margin: Inset{left: 250.0 right: 0 top: 102.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "fri" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    View{ width: 26.3 height: 26.0 margin: Inset{left: 250.2 right: 0 top: 111.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "15" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 21.7 height: 15.5 margin: Inset{left: 296.0 right: 0 top: 102.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "sat" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    View{ width: 26.3 height: 26.0 margin: Inset{left: 296.8 right: 0 top: 111.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "16" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 23.7 height: 15.5 margin: Inset{left: 341.8 right: 0 top: 102.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "sun" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    View{ width: 26.3 height: 26.0 margin: Inset{left: 344.0 right: 0 top: 111.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "17" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    RoundedView{ width: 375.0 height: 90.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 331.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 299.5 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 20.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    View{ width: 99.0 height: 18.9 margin: Inset{left: 59.0 right: 0 top: 36.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "March" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    Image{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/9529b95a64a3d054.png") }
    View{ width: 55.9 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #13131566 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #131315ff draw_bg.border_radius: 1.4 }
    Image{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/9555b9ae4e9df132.png") }
    Image{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/efd8e387ca373f22.png") }
    Image{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/21f19e633b0d4992.png") }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #121217ff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
}
