// FROZEN compile of ⟶ [Calendar] View #9 — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    View{ width: 31.4 height: 15.5 margin: Inset{left: 29.0 right: 0 top: 339.5 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "06:00" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 290.0 height: 90.0 margin: Inset{left: 70.0 right: 0 top: 339.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 7.5 }
    View{ width: 53.6 height: 16.0 margin: Inset{left: 107.8 right: 0 top: 407.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "War Room" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 17.8 height: 15.0 margin: Inset{left: 90.0 right: 0 top: 404.5 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 10.7 height: 9.0 margin: Inset{left: 93.5 right: 0 top: 407.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/a8f7bc0e4f2f7142.png") }
    View{ width: 77.6 height: 17.0 margin: Inset{left: 90.0 right: 0 top: 372.1 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "06:00 - 7:30" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 247.5 height: 19.5 margin: Inset{left: 90.0 right: 0 top: 354.6 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Morning cardio with Marie" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    Image{ width: 18.4 height: 20.0 margin: Inset{left: 306.5 right: 0 top: 394.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/b9ad62697dc49b49.png") }
    RoundedView{ width: 20.0 height: 20.0 margin: Inset{left: 324.9 right: 0 top: 394.5 bottom: 0} draw_bg.color: #ffffff66 draw_bg.border_radius: 10.0 }
    RoundedView{ width: 290.0 height: 103.5 margin: Inset{left: 70.0 right: 0 top: 639.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 7.5 }
    View{ width: 53.6 height: 17.5 margin: Inset{left: 107.8 right: 0 top: 717.1 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "War Room" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 17.8 height: 17.2 margin: Inset{left: 90.0 right: 0 top: 714.2 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 10.7 height: 10.3 margin: Inset{left: 93.5 right: 0 top: 717.7 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/55e4519ae7697328.png") }
    View{ width: 77.6 height: 18.6 margin: Inset{left: 90.0 right: 0 top: 677.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "09:00 - 11:00" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 247.5 height: 21.5 margin: Inset{left: 90.0 right: 0 top: 656.9 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Mobile Design System components review" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    Image{ width: 18.4 height: 20.0 margin: Inset{left: 306.4 right: 0 top: 708.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/b9ad62697dc49b49.png") }
    Image{ width: 18.4 height: 20.0 margin: Inset{left: 288.0 right: 0 top: 708.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/b9ad62697dc49b49.png") }
    RoundedView{ width: 20.0 height: 20.0 margin: Inset{left: 324.8 right: 0 top: 708.0 bottom: 0} draw_bg.color: #ffffff66 draw_bg.border_radius: 10.0 }
    View{ width: 31.4 height: 15.5 margin: Inset{left: 29.0 right: 0 top: 639.5 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "09:00" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 290.0 height: 90.0 margin: Inset{left: 70.0 right: 0 top: 479.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 7.5 }
    View{ width: 53.6 height: 16.0 margin: Inset{left: 107.8 right: 0 top: 547.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "War Room" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 17.8 height: 15.0 margin: Inset{left: 90.0 right: 0 top: 544.5 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 10.7 height: 9.0 margin: Inset{left: 93.5 right: 0 top: 547.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/a8f7bc0e4f2f7142.png") }
    View{ width: 77.6 height: 17.0 margin: Inset{left: 90.0 right: 0 top: 512.1 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "08:00 - 8:30" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 247.5 height: 19.5 margin: Inset{left: 90.0 right: 0 top: 494.6 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Design team daily stand-up" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 31.9 height: 15.5 margin: Inset{left: 28.0 right: 0 top: 479.5 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "08:00" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 290.0 height: 32.5 margin: Inset{left: 70.0 right: 0 top: 753.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 4.9 }
    RoundedView{ width: 290.0 height: 32.5 margin: Inset{left: 70.0 right: 0 top: 753.0 bottom: 0} draw_bg.color: #d8d8d824 draw_bg.border_radius: 4.9 }
    View{ width: 30.8 height: 15.5 margin: Inset{left: 29.0 right: 0 top: 754.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "08:30" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 290.0 height: 49.5 margin: Inset{left: 70.0 right: 0 top: 280.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 7.5 }
    RoundedView{ width: 290.0 height: 49.5 margin: Inset{left: 70.0 right: 0 top: 280.0 bottom: 0} draw_bg.color: #d8d8d824 draw_bg.border_radius: 7.5 }
    RoundedView{ width: 290.0 height: 30.0 margin: Inset{left: 70.0 right: 0 top: 439.5 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 4.5 }
    RoundedView{ width: 290.0 height: 30.0 margin: Inset{left: 70.0 right: 0 top: 439.5 bottom: 0} draw_bg.color: #d8d8d824 draw_bg.border_radius: 4.5 }
    View{ width: 30.8 height: 15.5 margin: Inset{left: 28.5 right: 0 top: 439.5 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "07:30" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    RoundedView{ width: 290.0 height: 50.0 margin: Inset{left: 70.0 right: 0 top: 579.5 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 7.5 }
    View{ width: 114.7 height: 17.0 margin: Inset{left: 112.5 right: 0 top: 599.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Pick up groceries" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 89.5 right: 0 top: 597.0 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 9.5 height: 7.1 margin: Inset{left: 92.5 right: 0 top: 600.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/7d35e6cc43cdfd69.png") }
    View{ width: 30.8 height: 15.5 margin: Inset{left: 29.5 right: 0 top: 579.5 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "08:30" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    Image{ width: 375.0 height: 224.9 margin: Inset{left: 0.0 right: 0 top: 90.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/896bb4b3b7120047.png") }
    RoundedView{ width: 25.0 height: 5.0 margin: Inset{left: 175.0 right: 0 top: 294.5 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 2.5 }
    RoundedView{ width: 335.0 height: 1.0 margin: Inset{left: 21.0 right: 0 top: 90.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 35.2 height: 19.5 margin: Inset{left: 20.2 right: 0 top: 106.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Mon" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 28.1 height: 19.5 margin: Inset{left: 74.5 right: 0 top: 106.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "tue" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 35.2 height: 19.5 margin: Inset{left: 121.8 right: 0 top: 106.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "wed" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 30.3 height: 19.5 margin: Inset{left: 175.0 right: 0 top: 106.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "thu" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 26.8 height: 19.5 margin: Inset{left: 229.0 right: 0 top: 106.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "fri" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 26.8 height: 19.5 margin: Inset{left: 278.2 right: 0 top: 106.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "sat" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 30.3 height: 19.5 margin: Inset{left: 327.5 right: 0 top: 106.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "sun" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 143.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "25" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 143.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "26" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 143.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "27" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 143.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "28" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 143.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "29" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 143.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "30" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 143.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "1" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 191.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "2" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 191.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "3" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 191.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "4" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 191.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "5" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 191.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "6" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 191.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "7" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 191.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "8" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 239.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "9" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 239.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "10" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 239.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "11" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 239.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "12" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 239.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "13" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 239.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "14" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 239.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "15" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 287.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "16" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 287.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "17" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 287.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "18" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 287.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "19" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 287.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "20" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 287.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "21" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 287.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "22" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 335.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "23" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 335.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "24" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 335.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "25" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 335.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "26" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 335.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "27" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 335.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "28" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 335.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "29" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 383.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "30" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 383.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "31" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 383.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "1" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 383.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "2" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 383.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "3" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 383.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "4" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 383.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "5" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 135.2 right: 0 top: 166.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 336.2 right: 0 top: 166.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 341.2 right: 0 top: 166.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 231.2 right: 0 top: 214.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 236.2 right: 0 top: 214.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 241.2 right: 0 top: 214.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 132.8 right: 0 top: 262.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 137.8 right: 0 top: 262.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 285.2 right: 0 top: 310.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 290.2 right: 0 top: 310.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 79.8 right: 0 top: 359.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 84.8 right: 0 top: 359.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 89.8 right: 0 top: 359.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 154.2 height: 30.0 margin: Inset{left: 84.0 right: 0 top: 182.5 bottom: 0} draw_bg.color: #4c5fefff }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 232.8 right: 0 top: 191.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "14" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.7 right: 0 top: 191.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "10" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 375.0 height: 90.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 331.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 299.5 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 20.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    View{ width: 99.0 height: 18.9 margin: Inset{left: 59.0 right: 0 top: 36.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "today, 5 Dec" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    Image{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/c30489d80e8e95b9.png") }
    View{ width: 55.9 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #13131566 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #131315ff draw_bg.border_radius: 1.4 }
    Image{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/e8d9dd540ef1f854.png") }
    Image{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/de5323857e422527.png") }
    Image{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/781917dad39669d8.png") }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #121217ff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    Image{ width: 365.0 height: 16.0 margin: Inset{left: 10.0 right: 0 top: 453.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/7fd57dab73d0d1bc.png") }
    View{ width: 30.8 height: 15.5 margin: Inset{left: 12.2 right: 0 top: 456.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "07:49" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
}
