// FROZEN compile of ⟶ [Calendar] View #1 — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    RoundedShadowView{ width: 375.0 height: 225.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.shadow_color: #3b4a7424 draw_bg.shadow_radius: 14.5 draw_bg.shadow_offset: vec2(0.0, 1.5) draw_bg.color: #ffffffff }
    RoundedView{ width: 375.0 height: 135.0 margin: Inset{left: 0.0 right: 0 top: 70.0 bottom: 0} draw_bg.color: #140f2600 draw_bg.color_2: #000000ff }
    RoundedView{ width: 375.0 height: 170.0 margin: Inset{left: 0.0 right: 0 top: 128.5 bottom: 0} draw_bg.color: #6b999fff draw_bg.border_radius: 20.0 }
    View{ width: 45.6 height: 19.5 margin: Inset{left: 141.0 right: 0 top: 153.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "10 m/s" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 79.2 height: 15.0 margin: Inset{left: 141.0 right: 0 top: 143.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "wind speed" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 118.0 right: 0 top: 147.5 bottom: 0} draw_bg.color: #1c8ff800 }
    View{ width: 45.6 height: 19.5 margin: Inset{left: 43.0 right: 0 top: 153.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "+26° C" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 60.5 height: 15.0 margin: Inset{left: 43.0 right: 0 top: 143.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "weather" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 20.0 right: 0 top: 147.5 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 10.1 height: 7.6 margin: Inset{left: 22.4 right: 0 top: 149.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/461d0c9a5350e408.png") }
    Image{ width: 2.8 height: 5.8 margin: Inset{left: 26.1 right: 0 top: 154.2 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/9e53a24e9abafb5f.png") }
    View{ width: 60.5 height: 19.5 margin: Inset{left: 256.0 right: 0 top: 153.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "756.9 mm" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 59.4 height: 15.0 margin: Inset{left: 256.0 right: 0 top: 143.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "uv index" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 233.0 right: 0 top: 147.5 bottom: 0} draw_bg.color: #1c8ff800 }
    View{ width: 25.9 height: 19.5 margin: Inset{left: 354.0 right: 0 top: 153.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "46%" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 61.1 height: 15.0 margin: Inset{left: 354.0 right: 0 top: 143.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "humidity" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 15.0 height: 15.0 margin: Inset{left: 331.0 right: 0 top: 147.5 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 7.5 height: 8.8 margin: Inset{left: 334.5 right: 0 top: 150.8 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/77021e33e371e146.png") }
    RoundedShadowView{ width: 375.0 height: 702.5 margin: Inset{left: 0.0 right: 0 top: 178.5 bottom: 0} draw_bg.shadow_color: #3b4a7433 draw_bg.shadow_radius: 18.0 draw_bg.shadow_offset: vec2(0.0, 3.0) draw_bg.color: #ffffffff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 335.0 height: 66.5 margin: Inset{left: 20.0 right: 0 top: 740.0 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 7.5 }
    RoundedShadowView{ width: 45.0 height: 51.5 margin: Inset{left: 30.0 right: 0 top: 747.5 bottom: 0} draw_bg.shadow_color: #3b4a7433 draw_bg.shadow_radius: 34.5 draw_bg.shadow_offset: vec2(0.0, 10.0) draw_bg.color: #ffffffff draw_bg.border_radius: 7.5 }
    RoundedView{ width: 45.0 height: 51.5 margin: Inset{left: 30.0 right: 0 top: 747.5 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 7.5 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 66.8 right: 0 top: 752.2 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.gradient_angle: 15.5 draw_bg.border_radius: 1.8 }
    View{ width: 23.7 height: 15.5 margin: Inset{left: 41.8 right: 0 top: 757.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "DEC" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    View{ width: 30.8 height: 30.5 margin: Inset{left: 42.2 right: 0 top: 766.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "10" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 12.4 } } }
    View{ width: 269.5 height: 23.0 margin: Inset{left: 92.5 right: 0 top: 772.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "On the other hand, we denounce with…" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 164.9 height: 21.0 margin: Inset{left: 92.5 right: 0 top: 755.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Annual Design Workshop" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 335.0 height: 66.5 margin: Inset{left: 20.0 right: 0 top: 669.5 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 7.5 }
    RoundedShadowView{ width: 45.0 height: 51.5 margin: Inset{left: 30.0 right: 0 top: 677.0 bottom: 0} draw_bg.shadow_color: #3b4a7433 draw_bg.shadow_radius: 34.5 draw_bg.shadow_offset: vec2(0.0, 10.0) draw_bg.color: #ffffffff draw_bg.border_radius: 7.5 }
    RoundedView{ width: 45.0 height: 51.5 margin: Inset{left: 30.0 right: 0 top: 677.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 7.5 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 66.8 right: 0 top: 681.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.gradient_angle: 15.5 draw_bg.border_radius: 1.8 }
    View{ width: 23.7 height: 15.5 margin: Inset{left: 41.8 right: 0 top: 687.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "DEC" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.0 } } }
    View{ width: 30.8 height: 30.5 margin: Inset{left: 42.2 right: 0 top: 696.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "10" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 12.4 } } }
    View{ width: 269.5 height: 23.0 margin: Inset{left: 92.5 right: 0 top: 701.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Until recently, the prevailing view assum…" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 132.0 height: 21.0 margin: Inset{left: 92.5 right: 0 top: 684.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Design Hackathon" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 625.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 152.3 height: 19.0 margin: Inset{left: 25.0 right: 0 top: 641.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Events • 10-14 December" draw_text.color: #3b3b4dff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 344.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "25" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 344.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "26" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 344.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "27" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 344.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "28" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 344.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "29" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 344.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "30" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 344.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "1" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 392.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "2" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 392.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "3" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 392.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "4" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 392.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "5" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 392.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "6" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 392.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "7" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 392.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "8" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 440.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "9" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 440.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "10" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 440.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "11" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 440.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "12" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 440.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "13" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 440.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "14" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 440.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "15" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 488.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "16" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 488.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "17" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 488.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "18" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 488.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "19" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 488.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "20" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 488.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "21" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 488.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "22" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 536.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "23" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 536.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "24" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 536.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "25" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 536.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "26" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 536.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "27" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 536.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "28" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 536.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "29" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 584.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "30" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 584.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "31" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 584.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "1" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 584.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "2" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 584.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "3" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 584.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "4" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 584.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "5" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 135.2 right: 0 top: 367.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.gradient_angle: 15.5 draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 336.2 right: 0 top: 367.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 341.2 right: 0 top: 367.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 231.2 right: 0 top: 415.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 236.2 right: 0 top: 415.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.gradient_angle: 15.5 draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 241.2 right: 0 top: 415.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 132.8 right: 0 top: 463.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 137.8 right: 0 top: 463.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 285.2 right: 0 top: 511.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 290.2 right: 0 top: 511.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.gradient_angle: 15.5 draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 79.8 right: 0 top: 560.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.gradient_angle: 15.5 draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 84.8 right: 0 top: 560.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 89.8 right: 0 top: 560.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 197.3 height: 30.0 margin: Inset{left: 87.5 right: 0 top: 431.5 bottom: 0} draw_bg.color: #4c5fefff }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 278.2 right: 0 top: 440.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "14" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 83.4 right: 0 top: 440.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "10" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 35.2 height: 19.5 margin: Inset{left: 19.2 right: 0 top: 304.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Mon" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 28.1 height: 19.5 margin: Inset{left: 73.5 right: 0 top: 304.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "tue" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 35.2 height: 19.5 margin: Inset{left: 120.8 right: 0 top: 304.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "wed" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 30.3 height: 19.5 margin: Inset{left: 174.0 right: 0 top: 304.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "thu" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 26.8 height: 19.5 margin: Inset{left: 228.0 right: 0 top: 304.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "fri" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 26.8 height: 19.5 margin: Inset{left: 277.2 right: 0 top: 304.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "sat" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 30.3 height: 19.5 margin: Inset{left: 326.5 right: 0 top: 304.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "sun" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 335.0 height: 1.0 margin: Inset{left: 20.0 right: 0 top: 288.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    RoundedView{ width: 375.0 height: 95.0 margin: Inset{left: 0.0 right: 0 top: 178.5 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 24.0 height: 20.8 margin: Inset{left: 20.0 right: 0 top: 202.7 bottom: 0} draw_bg.color: #1c8ff800 }
    RoundedView{ width: 24.0 height: 20.8 margin: Inset{left: 299.5 right: 0 top: 202.7 bottom: 0} draw_bg.color: #50a1ff00 }
    RoundedView{ width: 24.0 height: 20.8 margin: Inset{left: 331.0 right: 0 top: 202.7 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 4.7 height: 8.2 margin: Inset{left: 337.0 right: 0 top: 209.2 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/dc1980931d038bb9.png") }
    View{ width: 139.2 height: 14.7 margin: Inset{left: 20.0 right: 0 top: 262.7 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Interaction Design Team" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 124.9 height: 28.9 margin: Inset{left: 20.0 right: 0 top: 236.8 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "May" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 14.9 } } }
    Image{ width: 27.4 height: 30.0 margin: Inset{left: 297.6 right: 0 top: 234.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/e97b4b93a15101bd.png") }
    Image{ width: 27.4 height: 30.0 margin: Inset{left: 270.0 right: 0 top: 234.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/e97b4b93a15101bd.png") }
    RoundedView{ width: 29.9 height: 30.0 margin: Inset{left: 325.1 right: 0 top: 234.0 bottom: 0} draw_bg.color: #ffffff66 draw_bg.border_radius: 15.0 }
    Image{ width: 375.0 height: 107.5 margin: Inset{left: 0.0 right: 0 top: 704.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/42e0c8b617ebc302.png") }
    Image{ width: 375.0 height: 107.5 margin: Inset{left: 0.0 right: 0 top: 704.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/42e0c8b617ebc302.png") }
    RoundedView{ width: 24.0 height: 30.4 margin: Inset{left: 325.5 right: 0 top: 748.1 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 12.0 }
    RoundedView{ width: 24.0 height: 30.4 margin: Inset{left: 175.5 right: 0 top: 748.1 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 17.5 height: 15.1 margin: Inset{left: 178.0 right: 0 top: 752.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/b3e2281ab521ae3e.png") }
    RoundedView{ width: 15.5 height: 17.1 margin: Inset{left: 191.0 right: 0 top: 748.1 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 3.5 }
    View{ width: 18.3 height: 17.4 margin: Inset{left: 193.2 right: 0 top: 751.3 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "10" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 24.0 height: 30.4 margin: Inset{left: 100.5 right: 0 top: 748.1 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 4.0 height: 5.1 margin: Inset{left: 115.5 right: 0 top: 767.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/dd20c0951425f5df.png") }
    RoundedView{ width: 24.0 height: 30.4 margin: Inset{left: 25.5 right: 0 top: 748.1 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 14.0 height: 19.6 margin: Inset{left: 31.0 right: 0 top: 753.8 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/26bfa000dc3d6bd7.png") }
    Image{ width: 4.7 height: 9.8 margin: Inset{left: 35.6 right: 0 top: 763.6 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/eb50966504eac202.png") }
    Image{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/21f19e633b0d4992.png") }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #121217ff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    Image{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/9529b95a64a3d054.png") }
    View{ width: 55.9 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #13131566 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #131315ff draw_bg.border_radius: 1.4 }
    Image{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/9555b9ae4e9df132.png") }
    Image{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/efd8e387ca373f22.png") }
}
