// FROZEN compile of ⟶ [Calendar] View #4 — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    View{ width: 35.2 height: 19.5 margin: Inset{left: 20.2 right: 0 top: 95.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Mon" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 28.1 height: 19.5 margin: Inset{left: 74.5 right: 0 top: 95.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "tue" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 35.2 height: 19.5 margin: Inset{left: 121.8 right: 0 top: 95.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "wed" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 30.3 height: 19.5 margin: Inset{left: 175.0 right: 0 top: 95.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "thu" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 26.8 height: 19.5 margin: Inset{left: 229.0 right: 0 top: 95.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "fri" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 26.8 height: 19.5 margin: Inset{left: 278.2 right: 0 top: 95.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "sat" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 30.3 height: 19.5 margin: Inset{left: 327.5 right: 0 top: 95.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "sun" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 375.0 height: 364.5 margin: Inset{left: 0.0 right: 0 top: 122.0 bottom: 0} draw_bg.color: #ffffffff }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 201.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "25" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 201.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "26" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 201.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "27" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 201.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "28" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 201.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "29" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 201.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "30" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 201.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "1" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 249.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "2" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 249.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "3" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 249.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "4" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 249.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "5" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 249.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "6" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 249.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "7" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 249.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "8" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 297.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "9" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 297.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "10" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 297.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "11" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 297.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "12" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 297.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "13" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 297.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "14" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 297.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "15" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 345.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "16" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 345.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "17" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 345.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "18" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 345.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "19" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 345.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "20" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 345.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "21" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 345.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "22" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 393.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "23" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 393.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "24" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 393.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "25" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 393.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "26" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 393.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "27" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 393.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "28" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 393.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "29" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 441.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "30" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 441.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "31" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 441.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "1" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 441.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "2" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 441.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "3" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 441.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "4" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 441.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "5" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 135.2 right: 0 top: 224.2 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.gradient_angle: 15.5 draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 336.2 right: 0 top: 224.2 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 341.2 right: 0 top: 224.2 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 231.2 right: 0 top: 272.2 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 236.2 right: 0 top: 272.2 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.gradient_angle: 15.5 draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 241.2 right: 0 top: 272.2 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 132.8 right: 0 top: 320.2 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 137.8 right: 0 top: 320.2 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 285.2 right: 0 top: 368.2 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 290.2 right: 0 top: 368.2 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.gradient_angle: 15.5 draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 79.8 right: 0 top: 417.2 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.gradient_angle: 15.5 draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 84.8 right: 0 top: 417.2 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 89.8 right: 0 top: 417.2 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 375.0 height: 50.0 margin: Inset{left: 0.0 right: 0 top: 122.0 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 375.0 height: 65.0 margin: Inset{left: 0.0 right: 0 top: 107.0 bottom: 0} draw_bg.color: #140f2600 draw_bg.color_2: #000000ff }
    View{ width: 129.9 height: 26.0 margin: Inset{left: 22.4 right: 0 top: 137.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "April" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    RoundedView{ width: 375.0 height: 364.5 margin: Inset{left: 0.0 right: 0 top: 486.5 bottom: 0} draw_bg.color: #ffffffff }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 565.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "25" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 565.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "26" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 565.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "27" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 565.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "28" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 565.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "29" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 565.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "30" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 565.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "1" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 613.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "2" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 613.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "3" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 613.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "4" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 613.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "5" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 613.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "6" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 613.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "7" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 613.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "8" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 661.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "9" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 661.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "10" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 661.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "11" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 661.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "12" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 661.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "13" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 661.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "14" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 661.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "15" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 709.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "16" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 709.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "17" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 709.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "18" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 709.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "19" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 709.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "20" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 709.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "21" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 709.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "22" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 757.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "23" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 757.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "24" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 757.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "25" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 757.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "26" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 757.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "27" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 757.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "28" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 757.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "29" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 805.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "30" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 805.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "31" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 805.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "1" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 805.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "2" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 805.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "3" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 805.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "4" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 805.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "5" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 135.2 right: 0 top: 588.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.gradient_angle: 15.5 draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 336.2 right: 0 top: 588.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 341.2 right: 0 top: 588.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 231.2 right: 0 top: 636.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 236.2 right: 0 top: 636.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.gradient_angle: 15.5 draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 241.2 right: 0 top: 636.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 132.8 right: 0 top: 684.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 137.8 right: 0 top: 684.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 285.2 right: 0 top: 732.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 290.2 right: 0 top: 732.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.gradient_angle: 15.5 draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 79.8 right: 0 top: 781.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.gradient_angle: 15.5 draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 84.8 right: 0 top: 781.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 89.8 right: 0 top: 781.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    View{ width: 115.5 height: 18.5 margin: Inset{left: 40.0 right: 0 top: 496.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "December" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    RoundedView{ width: 375.0 height: 50.0 margin: Inset{left: 0.0 right: 0 top: 486.5 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 375.0 height: 65.0 margin: Inset{left: 0.0 right: 0 top: 471.5 bottom: 0} draw_bg.color: #140f2600 draw_bg.color_2: #000000ff }
    View{ width: 129.9 height: 26.0 margin: Inset{left: 22.4 right: 0 top: 501.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "May" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    Image{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/21f19e633b0d4992.png") }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #121217ff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    RoundedView{ width: 375.0 height: 90.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 331.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 4.0 height: 5.2 margin: Inset{left: 345.9 right: 0 top: 55.2 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/dd20c0951425f5df.png") }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 299.5 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 20.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 4.7 height: 12.2 margin: Inset{left: 26.0 right: 0 top: 45.6 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/0cf18175c90bad72.png") }
    View{ width: 99.0 height: 18.9 margin: Inset{left: 59.0 right: 0 top: 36.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "2020" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    Image{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/9529b95a64a3d054.png") }
    View{ width: 55.9 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #13131566 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #131315ff draw_bg.border_radius: 1.4 }
    Image{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/9555b9ae4e9df132.png") }
    Image{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/efd8e387ca373f22.png") }
}
