// FROZEN compile of ⟶ [Calendar] View #8 — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    RoundedView{ width: 375.0 height: 812.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #140f26cc }
    RoundedView{ width: 375.0 height: 720.0 margin: Inset{left: 0.0 right: 0 top: 93.5 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 30.0 height: 30.0 margin: Inset{left: 287.0 right: 0 top: 113.5 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 15.0 }
    RoundedView{ width: 10.3 height: 10.3 margin: Inset{left: 296.9 right: 0 top: 123.3 bottom: 0} draw_bg.color: #1c8ff800 }
    RoundedView{ width: 6.5 height: 6.5 margin: Inset{left: 298.8 right: 0 top: 125.3 bottom: 0} draw_bg.color: #50a1ff00 }
    RoundedView{ width: 30.0 height: 30.0 margin: Inset{left: 325.0 right: 0 top: 113.5 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 15.0 }
    RoundedView{ width: 10.3 height: 10.3 margin: Inset{left: 334.9 right: 0 top: 123.3 bottom: 0} draw_bg.color: #1c8ff800 }
    RoundedView{ width: 6.5 height: 6.5 margin: Inset{left: 336.8 right: 0 top: 125.3 bottom: 0} draw_bg.color: #50a1ff00 }
    View{ width: 112.2 height: 26.0 margin: Inset{left: 20.0 right: 0 top: 114.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "January 2020" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    RoundedView{ width: 335.0 height: 1.0 margin: Inset{left: 20.0 right: 0 top: 153.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 209.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "25" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 209.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "26" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 209.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "27" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 209.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "28" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 209.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "29" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 209.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "30" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 209.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "1" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 257.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "2" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 257.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "3" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 257.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "4" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 257.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "5" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 257.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "6" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 257.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "7" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 257.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "8" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 305.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "9" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 305.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "10" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 305.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "11" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 305.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "12" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 305.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "13" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 305.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "14" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 305.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "15" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 353.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "16" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 353.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "17" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 353.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "18" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 353.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "19" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 353.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "20" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 353.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "21" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 353.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "22" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 401.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "23" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 401.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "24" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 401.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "25" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 401.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "26" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 401.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "27" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 401.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "28" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 401.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "29" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 29.8 right: 0 top: 449.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "30" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 17.0 margin: Inset{left: 80.6 right: 0 top: 449.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "31" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 131.4 right: 0 top: 449.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "1" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 182.2 right: 0 top: 449.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "2" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 233.1 right: 0 top: 449.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "3" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 283.9 right: 0 top: 449.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "4" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 14.3 height: 17.0 margin: Inset{left: 334.8 right: 0 top: 449.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "5" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 135.2 right: 0 top: 232.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 336.2 right: 0 top: 232.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 341.2 right: 0 top: 232.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 231.2 right: 0 top: 280.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 236.2 right: 0 top: 280.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 241.2 right: 0 top: 280.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 132.8 right: 0 top: 328.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 137.8 right: 0 top: 328.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 285.2 right: 0 top: 376.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 290.2 right: 0 top: 376.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 79.8 right: 0 top: 425.8 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 84.8 right: 0 top: 425.8 bottom: 0} draw_bg.color: #dfe5eeff draw_bg.border_radius: 1.8 }
    RoundedView{ width: 3.5 height: 3.5 margin: Inset{left: 89.8 right: 0 top: 425.8 bottom: 0} draw_bg.color: #ff464bff draw_bg.border_radius: 1.8 }
    View{ width: 35.2 height: 19.5 margin: Inset{left: 20.2 right: 0 top: 169.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Mon" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 28.1 height: 19.5 margin: Inset{left: 74.5 right: 0 top: 169.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "tue" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 35.2 height: 19.5 margin: Inset{left: 121.8 right: 0 top: 169.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "wed" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 30.3 height: 19.5 margin: Inset{left: 175.0 right: 0 top: 169.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "thu" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 26.8 height: 19.5 margin: Inset{left: 229.0 right: 0 top: 169.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "fri" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 26.8 height: 19.5 margin: Inset{left: 278.2 right: 0 top: 169.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "sat" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 30.3 height: 19.5 margin: Inset{left: 327.5 right: 0 top: 169.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "sun" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedShadowView{ width: 375.0 height: 318.5 margin: Inset{left: 0.0 right: 0 top: 497.5 bottom: 0} draw_bg.shadow_color: #3b4a7432 draw_bg.shadow_radius: 34.5 draw_bg.shadow_offset: vec2(0.0, 10.0) draw_bg.color: #ffffffff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 325.0 height: 40.0 margin: Inset{left: 25.0 right: 0 top: 707.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 6.0 }
    RoundedView{ width: 52.0 height: 19.2 margin: Inset{left: 59.6 right: 0 top: 717.9 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 8.4 height: 6.2 margin: Inset{left: 72.7 right: 0 top: 722.7 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/ab232621793f763a.png") }
    Image{ width: 27.1 height: 6.9 margin: Inset{left: 72.7 right: 0 top: 725.8 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/29f8c329e73e53ad.png") }
    View{ width: 209.7 height: 14.0 margin: Inset{left: 124.7 right: 0 top: 723.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "create event" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    RoundedView{ width: 375.0 height: 60.0 margin: Inset{left: 0.5 right: 0 top: 497.5 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.5 right: 0 top: 556.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 224.0 height: 28.5 margin: Inset{left: 127.4 right: 0 top: 516.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "11 Jan, 2020" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.4 } } }
    View{ width: 69.8 height: 16.0 margin: Inset{left: 23.6 right: 0 top: 522.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Date" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 375.0 height: 60.0 margin: Inset{left: 0.5 right: 0 top: 617.5 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.5 right: 0 top: 676.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 224.0 height: 28.5 margin: Inset{left: 127.4 right: 0 top: 636.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Hall of Justice" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.4 } } }
    View{ width: 69.8 height: 16.0 margin: Inset{left: 23.6 right: 0 top: 642.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Location" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 375.0 height: 60.0 margin: Inset{left: 0.5 right: 0 top: 557.5 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.5 right: 0 top: 616.5 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 76.4 height: 16.0 margin: Inset{left: 23.6 right: 0 top: 582.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Participants" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    Image{ width: 27.5 height: 30.0 margin: Inset{left: 136.1 right: 0 top: 572.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/1b605d3e50ec2dc8.png") }
    Image{ width: 27.5 height: 30.0 margin: Inset{left: 108.5 right: 0 top: 572.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/1b605d3e50ec2dc8.png") }
    Image{ width: 27.5 height: 30.0 margin: Inset{left: 163.6 right: 0 top: 572.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/1b605d3e50ec2dc8.png") }
    Image{ width: 27.5 height: 30.0 margin: Inset{left: 191.3 right: 0 top: 572.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/1b605d3e50ec2dc8.png") }
    Image{ width: 27.5 height: 30.0 margin: Inset{left: 218.9 right: 0 top: 572.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/1b605d3e50ec2dc8.png") }
    RoundedView{ width: 30.0 height: 30.0 margin: Inset{left: 246.5 right: 0 top: 572.5 bottom: 0} draw_bg.color: #ffffff66 draw_bg.border_radius: 15.0 }
    RoundedView{ width: 30.0 height: 30.0 margin: Inset{left: 246.5 right: 0 top: 572.5 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 15.0 }
    RoundedView{ width: 10.3 height: 10.3 margin: Inset{left: 256.4 right: 0 top: 582.4 bottom: 0} draw_bg.color: #1c8ff800 }
    RoundedView{ width: 6.5 height: 6.5 margin: Inset{left: 258.3 right: 0 top: 584.3 bottom: 0} draw_bg.color: #50a1ff00 }
    Image{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/781917dad39669d8.png") }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #121217ff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    Image{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/dbbd9db129e5adec.png") }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #ffffff66 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 1.4 }
    Image{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/f9e85dd1496baadf.png") }
    Image{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/47adc1dc07e11640.png") }
    View{ width: 55.9 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
}
