// FROZEN compile of ⟶ [Shop] View #18 — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    Image{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/781917dad39669d8.png") }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #121217ff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    RoundedView{ width: 375.0 height: 90.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 331.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 20.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 4.7 height: 12.2 margin: Inset{left: 26.0 right: 0 top: 45.6 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/a4d2ee5ac0a1c9a7.png") }
    View{ width: 99.0 height: 18.9 margin: Inset{left: 59.0 right: 0 top: 36.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Checkout" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    Image{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/c30489d80e8e95b9.png") }
    View{ width: 55.9 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #13131566 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #131315ff draw_bg.border_radius: 1.4 }
    Image{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/e8d9dd540ef1f854.png") }
    Image{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/de5323857e422527.png") }
    RoundedView{ width: 335.0 height: 115.0 margin: Inset{left: 20.0 right: 0 top: 210.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 7.5 }
    RoundedView{ width: 375.0 height: 40.0 margin: Inset{left: 0.0 right: 0 top: 90.0 bottom: 0} draw_bg.color: #ffffffff }
    RoundedView{ width: 19.8 height: 18.0 margin: Inset{left: 82.6 right: 0 top: 85.5 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 9.0 }
    RoundedView{ width: 16.5 height: 15.0 margin: Inset{left: 84.2 right: 0 top: 87.0 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 10.4 height: 10.3 margin: Inset{left: 87.5 right: 0 top: 89.1 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/dfbe483cb42627eb.png") }
    View{ width: 53.6 height: 16.0 margin: Inset{left: 79.0 right: 0 top: 109.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Delivery" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 25.2 height: 18.0 margin: Inset{left: 174.9 right: 0 top: 85.5 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 9.0 }
    RoundedView{ width: 21.0 height: 15.0 margin: Inset{left: 177.0 right: 0 top: 87.0 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 11.3 height: 7.7 margin: Inset{left: 183.2 right: 0 top: 90.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/b8dc55a8f9dcc7b6.png") }
    Image{ width: 9.3 height: 6.3 margin: Inset{left: 181.2 right: 0 top: 93.2 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/455bf455b8573e9f.png") }
    View{ width: 76.4 height: 16.0 margin: Inset{left: 170.3 right: 0 top: 109.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Confirmation" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 19.8 height: 18.0 margin: Inset{left: 272.6 right: 0 top: 85.5 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 9.0 }
    RoundedView{ width: 16.5 height: 15.0 margin: Inset{left: 274.2 right: 0 top: 87.0 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 9.3 height: 9.5 margin: Inset{left: 278.1 right: 0 top: 90.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/af4f8fb2e875cdc7.png") }
    View{ width: 47.9 height: 16.0 margin: Inset{left: 269.1 right: 0 top: 109.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Payment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 129.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 20.5 height: 19.5 margin: Inset{left: 324.5 right: 0 top: 445.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "x1" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 33.1 height: 19.5 margin: Inset{left: 324.5 right: 0 top: 460.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$295" draw_text.color: #5882f2ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 220.0 height: 20.0 margin: Inset{left: 82.5 right: 0 top: 457.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Marshall puts out more than iconic..." draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 188.7 height: 19.5 margin: Inset{left: 82.5 right: 0 top: 441.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Grado Prestige SR325e" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 45.0 height: 45.0 margin: Inset{left: 20.0 right: 0 top: 436.5 bottom: 0} draw_bg.color: #e3e3e3ff draw_bg.border_radius: 7.5 }
    View{ width: 20.5 height: 19.5 margin: Inset{left: 324.5 right: 0 top: 384.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "x1" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 33.1 height: 19.5 margin: Inset{left: 324.5 right: 0 top: 399.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$295" draw_text.color: #5882f2ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 220.0 height: 20.0 margin: Inset{left: 82.5 right: 0 top: 396.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Marshall puts out more than iconic..." draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 188.7 height: 19.5 margin: Inset{left: 82.5 right: 0 top: 380.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Grado Prestige SR325e" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 45.0 height: 45.0 margin: Inset{left: 20.0 right: 0 top: 375.5 bottom: 0} draw_bg.color: #e3e3e3ff draw_bg.border_radius: 7.5 }
    View{ width: 115.5 height: 17.0 margin: Inset{left: 20.0 right: 0 top: 344.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Order summary" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 212.3 height: 17.0 margin: Inset{left: 162.0 right: 0 top: 344.5 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Total: $1312.00" draw_text.color: #131315ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 20.5 height: 19.5 margin: Inset{left: 324.5 right: 0 top: 506.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "x1" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 33.1 height: 19.5 margin: Inset{left: 324.5 right: 0 top: 521.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$399" draw_text.color: #5882f2ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 220.0 height: 20.0 margin: Inset{left: 82.5 right: 0 top: 518.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Marshall puts out more than iconic..." draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 188.7 height: 19.5 margin: Inset{left: 82.5 right: 0 top: 502.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Bose Noise Cancelling 700" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 45.0 height: 45.0 margin: Inset{left: 20.0 right: 0 top: 497.5 bottom: 0} draw_bg.color: #e3e3e3ff draw_bg.border_radius: 7.5 }
    View{ width: 20.5 height: 19.5 margin: Inset{left: 324.5 right: 0 top: 567.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "x1" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 33.1 height: 19.5 margin: Inset{left: 324.5 right: 0 top: 582.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$399" draw_text.color: #5882f2ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 220.0 height: 20.0 margin: Inset{left: 82.5 right: 0 top: 579.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Marshall puts out more than iconic..." draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 188.7 height: 19.5 margin: Inset{left: 82.5 right: 0 top: 563.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Bose Noise Cancelling 700" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    RoundedView{ width: 45.0 height: 45.0 margin: Inset{left: 20.0 right: 0 top: 558.5 bottom: 0} draw_bg.color: #e3e3e3ff draw_bg.border_radius: 7.5 }
    View{ width: 63.8 height: 17.0 margin: Inset{left: 20.0 right: 0 top: 150.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Shipping" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 295.0 height: 36.0 margin: Inset{left: 20.0 right: 0 top: 167.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fill height: Fit text: "Delivery is scheduled for today between 14:00 - 18:00 on 913 Bear Hill Street Flushing, NY 11354." draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Regular.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 line_spacing: 2.0 } } }
    RoundedView{ width: 30.0 height: 30.0 margin: Inset{left: 325.0 right: 0 top: 160.5 bottom: 0} draw_bg.color: #f4f6f9ff draw_bg.border_radius: 15.0 }
    RoundedView{ width: 6.5 height: 6.5 margin: Inset{left: 336.8 right: 0 top: 172.3 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 3.0 height: 2.9 margin: Inset{left: 338.3 right: 0 top: 173.6 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/7781a83f5a1ac8af.png") }
    RoundedView{ width: 335.0 height: 40.0 margin: Inset{left: 20.0 right: 0 top: 707.0 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 6.0 }
    View{ width: 216.2 height: 14.0 margin: Inset{left: 122.8 right: 0 top: 723.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Continue with payment" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
}
