// FROZEN compile of ⟶ [Social] Contacts #1 — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    RoundedView{ width: 375.0 height: 812.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 309.0 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 85.0 height: 25.0 margin: Inset{left: 275.0 right: 0 top: 262.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 12.5 }
    RoundedView{ width: 12.8 height: 15.0 margin: Inset{left: 311.1 right: 0 top: 267.5 bottom: 0} draw_bg.color: #50a1ff00 }
    View{ width: 61.2 height: 17.0 margin: Inset{left: 289.9 right: 0 top: 269.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "follow" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 25.0 right: 0 top: 255.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    View{ width: 105.0 height: 16.0 margin: Inset{left: 84.5 right: 0 top: 279.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Wintheiserborough" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 107.8 height: 21.0 margin: Inset{left: 85.0 right: 0 top: 261.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Estelle Holmes" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 379.0 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 85.0 height: 25.0 margin: Inset{left: 275.0 right: 0 top: 332.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 12.5 }
    RoundedView{ width: 12.8 height: 15.0 margin: Inset{left: 311.1 right: 0 top: 337.5 bottom: 0} draw_bg.color: #50a1ff00 }
    View{ width: 61.2 height: 17.0 margin: Inset{left: 289.9 right: 0 top: 339.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "follow" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 25.0 right: 0 top: 325.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    View{ width: 94.1 height: 16.0 margin: Inset{left: 84.5 right: 0 top: 349.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Mayeview" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 65.0 height: 21.0 margin: Inset{left: 85.0 right: 0 top: 331.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Ada Pena" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 449.0 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 85.0 height: 25.0 margin: Inset{left: 275.0 right: 0 top: 402.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 12.5 }
    RoundedView{ width: 12.8 height: 15.0 margin: Inset{left: 311.1 right: 0 top: 407.5 bottom: 0} draw_bg.color: #50a1ff00 }
    View{ width: 61.2 height: 17.0 margin: Inset{left: 289.9 right: 0 top: 409.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "follow" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 25.0 right: 0 top: 395.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    View{ width: 94.1 height: 16.0 margin: Inset{left: 84.5 right: 0 top: 419.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Newelltown" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 100.7 height: 21.0 margin: Inset{left: 85.0 right: 0 top: 401.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Kathryn Doyle" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 519.0 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 85.0 height: 25.0 margin: Inset{left: 275.0 right: 0 top: 472.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 12.5 }
    RoundedView{ width: 12.8 height: 15.0 margin: Inset{left: 311.1 right: 0 top: 477.5 bottom: 0} draw_bg.color: #50a1ff00 }
    View{ width: 61.2 height: 17.0 margin: Inset{left: 289.9 right: 0 top: 479.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "follow" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 25.0 right: 0 top: 465.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    View{ width: 94.1 height: 16.0 margin: Inset{left: 84.5 right: 0 top: 489.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Charlesstad" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 107.8 height: 21.0 margin: Inset{left: 85.0 right: 0 top: 471.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Helen Townsend" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 589.0 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 85.0 height: 25.0 margin: Inset{left: 275.0 right: 0 top: 542.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 12.5 }
    RoundedView{ width: 12.8 height: 15.0 margin: Inset{left: 311.1 right: 0 top: 547.5 bottom: 0} draw_bg.color: #50a1ff00 }
    View{ width: 61.2 height: 17.0 margin: Inset{left: 289.9 right: 0 top: 549.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "follow" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 25.0 right: 0 top: 535.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    View{ width: 94.1 height: 16.0 margin: Inset{left: 84.5 right: 0 top: 559.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "East Reinhold" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 107.8 height: 21.0 margin: Inset{left: 85.0 right: 0 top: 541.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Mattie Carlson" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 659.0 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 85.0 height: 25.0 margin: Inset{left: 275.0 right: 0 top: 612.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 12.5 }
    RoundedView{ width: 12.8 height: 15.0 margin: Inset{left: 311.1 right: 0 top: 617.5 bottom: 0} draw_bg.color: #50a1ff00 }
    View{ width: 61.2 height: 17.0 margin: Inset{left: 289.9 right: 0 top: 619.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "follow" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 25.0 right: 0 top: 605.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    View{ width: 99.3 height: 16.0 margin: Inset{left: 84.5 right: 0 top: 629.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Stoltenberghaven" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 86.4 height: 21.0 margin: Inset{left: 85.0 right: 0 top: 611.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Jean Weaver" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 375.0 height: 1.0 margin: Inset{left: 0.0 right: 0 top: 729.0 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 85.0 height: 25.0 margin: Inset{left: 275.0 right: 0 top: 682.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 12.5 }
    RoundedView{ width: 12.8 height: 15.0 margin: Inset{left: 311.1 right: 0 top: 687.5 bottom: 0} draw_bg.color: #50a1ff00 }
    View{ width: 61.2 height: 17.0 margin: Inset{left: 289.9 right: 0 top: 689.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "follow" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 25.0 right: 0 top: 675.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 20.0 }
    View{ width: 94.1 height: 16.0 margin: Inset{left: 84.5 right: 0 top: 699.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Hettingerstad" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 79.3 height: 21.0 margin: Inset{left: 85.0 right: 0 top: 681.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Lena Poole" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 25.0 right: 0 top: 95.0 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 33.0 right: 0 top: 103.0 bottom: 0} draw_bg.color: #50a1ff00 }
    View{ width: 20.5 height: 19.5 margin: Inset{left: 36.0 right: 0 top: 108.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "AB" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 150.6 height: 21.0 margin: Inset{left: 85.0 right: 0 top: 107.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Import from Facebook" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 40.0 height: 40.0 margin: Inset{left: 25.0 right: 0 top: 145.0 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.border_radius: 20.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 33.0 right: 0 top: 153.0 bottom: 0} draw_bg.color: #50a1ff00 }
    View{ width: 20.5 height: 19.5 margin: Inset{left: 36.0 right: 0 top: 158.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "AB" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 143.5 height: 21.0 margin: Inset{left: 85.0 right: 0 top: 157.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Import from Twitter" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 331.0 right: 0 top: 208.0 bottom: 0} draw_bg.color: #50a1ff00 }
    View{ width: 100.4 height: 17.0 margin: Inset{left: 25.0 right: 0 top: 214.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Suggested contacts" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 375.0 height: 90.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 331.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 4.0 height: 5.2 margin: Inset{left: 345.9 right: 0 top: 55.2 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/25109b7247d78546.png") }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 20.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 9.5 height: 12.2 margin: Inset{left: 27.5 right: 0 top: 45.6 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/ef894d24764b52b7.png") }
    Image{ width: 9.5 height: 12.2 margin: Inset{left: 27.5 right: 0 top: 45.6 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/963b7e5b855502b3.png") }
    View{ width: 99.0 height: 18.9 margin: Inset{left: 142.5 right: 0 top: 36.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Find contact" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    Image{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/d5c153885dd141a3.png") }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    Image{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/dbbd9db129e5adec.png") }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #ffffff66 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 1.4 }
    Image{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/f9e85dd1496baadf.png") }
    Image{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/47adc1dc07e11640.png") }
    View{ width: 55.9 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
}
