// FROZEN compile of ⟶ [Stats] Data visualization #1 — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    RoundedView{ width: 375.0 height: 812.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 345.0 height: 240.0 margin: Inset{left: 15.0 right: 0 top: 90.0 bottom: 0} draw_bg.color: #2dc9ebff draw_bg.color_2: #14d2b8ff draw_bg.gradient_angle: 15.5 draw_bg.border_radius: 15.0 }
    View{ width: 33.7 height: 13.8 margin: Inset{left: 312.9 right: 0 top: 116.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "table" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 33.7 height: 13.8 margin: Inset{left: 253.3 right: 0 top: 116.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Chart" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 45.6 height: 17.0 margin: Inset{left: 35.0 right: 0 top: 127.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$52721" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 67.9 height: 26.0 margin: Inset{left: 35.0 right: 0 top: 105.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Savings" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    View{ width: 25.9 height: 17.0 margin: Inset{left: 35.0 right: 0 top: 161.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "100" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 29.7 height: 17.0 margin: Inset{left: 35.0 right: 0 top: 212.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "50" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 306.5 height: 1.0 margin: Inset{left: 35.0 right: 0 top: 228.0 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 306.5 height: 1.0 margin: Inset{left: 35.0 right: 0 top: 177.0 bottom: 0} draw_bg.color: #ffffff0e }
    View{ width: 25.9 height: 17.0 margin: Inset{left: 35.0 right: 0 top: 263.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "0" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 29.7 height: 17.0 margin: Inset{left: 34.0 right: 0 top: 299.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Jan" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 26.4 height: 17.0 margin: Inset{left: 318.8 right: 0 top: 299.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Jun" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 28.1 height: 17.0 margin: Inset{left: 261.5 right: 0 top: 299.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "May" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 27.0 height: 17.0 margin: Inset{left: 205.5 right: 0 top: 299.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Apr" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 29.2 height: 17.0 margin: Inset{left: 147.0 right: 0 top: 299.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Mar" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 25.9 height: 17.0 margin: Inset{left: 92.5 right: 0 top: 299.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Feb" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    Image{ width: 288.1 height: 99.0 margin: Inset{left: 53.5 right: 0 top: 180.2 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/6ffbe8f21d16dc84.png") }
    Image{ width: 288.0 height: 77.7 margin: Inset{left: 53.5 right: 0 top: 180.2 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/d7c985b270ae3190.png") }
    RoundedView{ width: 33.5 height: 20.0 margin: Inset{left: 156.0 right: 0 top: 171.5 bottom: 0} draw_bg.color: #140f2693 draw_bg.border_radius: 3.7 }
    RoundedView{ width: 6.0 height: 10.0 margin: Inset{left: 156.0 right: 0 top: 186.5 bottom: 0} draw_bg.color: #140f2693 }
    Image{ width: 33.5 height: 25.0 margin: Inset{left: 156.0 right: 0 top: 171.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/57ac114f6fb6f543.png") }
    View{ width: 31.1 height: 17.0 margin: Inset{left: 158.6 right: 0 top: 176.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$501" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 345.0 height: 240.0 margin: Inset{left: 15.0 right: 0 top: 340.0 bottom: 0} draw_bg.color: #645affff draw_bg.color_2: #a573ffff draw_bg.gradient_angle: -134.3 draw_bg.border_radius: 15.0 }
    View{ width: 33.7 height: 13.8 margin: Inset{left: 312.9 right: 0 top: 366.1 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "table" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 33.7 height: 13.8 margin: Inset{left: 253.3 right: 0 top: 366.1 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Chart" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 145.8 height: 17.0 margin: Inset{left: 35.0 right: 0 top: 377.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$75948" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 104.5 height: 26.0 margin: Inset{left: 35.0 right: 0 top: 355.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Investments" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    View{ width: 25.9 height: 17.0 margin: Inset{left: 35.0 right: 0 top: 411.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "100" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 29.7 height: 17.0 margin: Inset{left: 35.0 right: 0 top: 462.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "50" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 306.5 height: 1.0 margin: Inset{left: 35.0 right: 0 top: 478.0 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 306.5 height: 1.0 margin: Inset{left: 35.0 right: 0 top: 427.0 bottom: 0} draw_bg.color: #ffffff0e }
    View{ width: 25.9 height: 17.0 margin: Inset{left: 35.0 right: 0 top: 513.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "0" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 29.7 height: 17.0 margin: Inset{left: 34.0 right: 0 top: 549.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Jan" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 26.4 height: 17.0 margin: Inset{left: 318.8 right: 0 top: 549.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Jun" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 28.1 height: 17.0 margin: Inset{left: 261.5 right: 0 top: 549.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "May" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 27.0 height: 17.0 margin: Inset{left: 205.5 right: 0 top: 549.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Apr" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 29.2 height: 17.0 margin: Inset{left: 147.0 right: 0 top: 549.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Mar" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 25.9 height: 17.0 margin: Inset{left: 92.5 right: 0 top: 549.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Feb" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    Image{ width: 287.8 height: 96.3 margin: Inset{left: 53.5 right: 0 top: 412.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/7de8d9877170d647.png") }
    Image{ width: 287.3 height: 112.2 margin: Inset{left: 53.5 right: 0 top: 413.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/620cbd66a242c8b8.png") }
    RoundedView{ width: 34.0 height: 20.0 margin: Inset{left: 158.5 right: 0 top: 430.5 bottom: 0} draw_bg.color: #140f2693 draw_bg.border_radius: 3.8 }
    RoundedView{ width: 6.0 height: 10.0 margin: Inset{left: 186.4 right: 0 top: 445.5 bottom: 0} draw_bg.color: #140f2693 }
    Image{ width: 34.0 height: 25.0 margin: Inset{left: 158.5 right: 0 top: 430.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/a5c97e3aea5e600e.png") }
    View{ width: 31.6 height: 17.0 margin: Inset{left: 161.2 right: 0 top: 435.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "$810" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 345.0 height: 240.0 margin: Inset{left: 15.0 right: 0 top: 590.0 bottom: 0} draw_bg.color: #ff8298ff draw_bg.color_2: #ffa073ff draw_bg.gradient_angle: 14.5 draw_bg.border_radius: 15.0 }
    View{ width: 33.7 height: 13.8 margin: Inset{left: 312.9 right: 0 top: 616.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "table" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 33.7 height: 13.8 margin: Inset{left: 253.3 right: 0 top: 616.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Chart" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 145.8 height: 17.0 margin: Inset{left: 35.0 right: 0 top: 627.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$8786" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.8 } } }
    View{ width: 79.2 height: 26.0 margin: Inset{left: 35.0 right: 0 top: 605.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Expenses" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.3 } } }
    View{ width: 25.9 height: 17.0 margin: Inset{left: 35.0 right: 0 top: 661.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "100" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 29.7 height: 17.0 margin: Inset{left: 35.0 right: 0 top: 712.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "50" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 306.5 height: 1.0 margin: Inset{left: 35.0 right: 0 top: 728.0 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 306.5 height: 1.0 margin: Inset{left: 35.0 right: 0 top: 677.0 bottom: 0} draw_bg.color: #ffffff0e }
    View{ width: 25.9 height: 17.0 margin: Inset{left: 35.0 right: 0 top: 763.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "0" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 29.7 height: 17.0 margin: Inset{left: 34.0 right: 0 top: 799.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Jan" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 26.4 height: 17.0 margin: Inset{left: 318.8 right: 0 top: 799.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Jun" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 28.1 height: 17.0 margin: Inset{left: 261.5 right: 0 top: 799.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "May" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 27.0 height: 17.0 margin: Inset{left: 205.5 right: 0 top: 799.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Apr" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 29.2 height: 17.0 margin: Inset{left: 147.0 right: 0 top: 799.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Mar" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 25.9 height: 17.0 margin: Inset{left: 92.5 right: 0 top: 799.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Feb" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    Image{ width: 287.0 height: 113.5 margin: Inset{left: 53.5 right: 0 top: 680.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/ae40b9fad7e2f22d.png") }
    Image{ width: 288.0 height: 83.0 margin: Inset{left: 53.5 right: 0 top: 680.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/c68cc24df52b48ee.png") }
    RoundedView{ width: 35.0 height: 20.0 margin: Inset{left: 168.5 right: 0 top: 711.0 bottom: 0} draw_bg.color: #140f2693 draw_bg.border_radius: 3.9 }
    RoundedView{ width: 6.2 height: 10.0 margin: Inset{left: 197.3 right: 0 top: 726.0 bottom: 0} draw_bg.color: #140f2693 }
    Image{ width: 35.0 height: 25.0 margin: Inset{left: 168.5 right: 0 top: 711.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/fbe7a70260ca6faf.png") }
    View{ width: 32.5 height: 17.0 margin: Inset{left: 171.2 right: 0 top: 715.5 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "$287" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 375.0 height: 90.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 331.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 8.3 height: 11.2 margin: Inset{left: 340.5 right: 0 top: 41.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/8688dc5623c55b16.png") }
    Image{ width: 11.9 height: 11.5 margin: Inset{left: 335.3 right: 0 top: 45.4 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/8e590e466d9f52ef.png") }
    Image{ width: 17.5 height: 22.5 margin: Inset{left: 334.5 right: 0 top: 40.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/ad763b8a1d98741e.png") }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 20.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 4.7 height: 12.2 margin: Inset{left: 26.0 right: 0 top: 45.6 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/24ed31ed1b20cbbe.png") }
    View{ width: 148.9 height: 18.9 margin: Inset{left: 59.0 right: 0 top: 36.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Transaction history" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    Image{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/e9e64c9a5ee483a3.png") }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #ffffff66 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 1.4 }
    Image{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/cc739ac0f046b01c.png") }
    Image{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/97cd7612f21eac70.png") }
    View{ width: 55.9 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
    Image{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/7c12dd4cca557c00.png") }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
}
