// FROZEN compile of ⟶ [Stats] Data visualization #3 — spec2dsl.py.
// A poster, not an app: no roles, no data, no theme.
View{ flow: Overlay width: 375 height: 812 draw_bg.color: #ffffffff
    RoundedView{ width: 375.0 height: 812.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 345.0 height: 285.0 margin: Inset{left: 15.0 right: 0 top: 140.0 bottom: 0} draw_bg.color: #23baffff draw_bg.color_2: #5183f0ff draw_bg.border_radius: 15.0 }
    RoundedView{ width: 41.5 height: 236.0 margin: Inset{left: 252.0 right: 0 top: 140.0 bottom: 0} draw_bg.color: #ffffff5f draw_bg.color_2: #ffffff07 }
    RoundedView{ width: 4.8 height: 4.5 margin: Inset{left: 287.0 right: 0 top: 397.5 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 2.2 }
    RoundedView{ width: 4.8 height: 4.5 margin: Inset{left: 335.2 right: 0 top: 397.5 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 2.2 }
    RoundedView{ width: 4.8 height: 4.5 margin: Inset{left: 318.8 right: 0 top: 397.5 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 2.2 }
    RoundedView{ width: 5.8 height: 5.5 margin: Inset{left: 302.4 right: 0 top: 397.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 2.8 }
    View{ width: 33.7 height: 13.8 margin: Inset{left: 155.5 right: 0 top: 396.6 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "table" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 33.7 height: 13.8 margin: Inset{left: 70.5 right: 0 top: 396.6 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Chart" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 345.0 height: 1.0 margin: Inset{left: 15.0 right: 0 top: 375.0 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 345.0 height: 1.0 margin: Inset{left: 15.0 right: 0 top: 189.0 bottom: 0} draw_bg.color: #ffffff0e }
    View{ width: 29.7 height: 17.0 margin: Inset{left: 34.0 right: 0 top: 160.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Jan" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 26.4 height: 17.0 margin: Inset{left: 316.2 right: 0 top: 160.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Jun" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 28.1 height: 17.0 margin: Inset{left: 260.0 right: 0 top: 160.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "May" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 27.0 height: 17.0 margin: Inset{left: 204.0 right: 0 top: 160.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Apr" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 29.2 height: 17.0 margin: Inset{left: 146.0 right: 0 top: 160.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Mar" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 25.9 height: 17.0 margin: Inset{left: 92.0 right: 0 top: 160.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Feb" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    Image{ width: 307.9 height: 83.0 margin: Inset{left: 33.5 right: 0 top: 258.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/288caaaad64309dc.png") }
    View{ width: 145.2 height: 41.0 margin: Inset{left: 35.0 right: 0 top: 210.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$4153.93" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 18.6 } } }
    View{ width: 134.8 height: 15.0 margin: Inset{left: 35.0 right: 0 top: 247.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "15th May - 15th June" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 33.0 height: 20.0 margin: Inset{left: 271.0 right: 0 top: 226.5 bottom: 0} draw_bg.color: #140f2693 draw_bg.border_radius: 3.6 }
    RoundedView{ width: 5.8 height: 10.0 margin: Inset{left: 271.0 right: 0 top: 241.5 bottom: 0} draw_bg.color: #140f2693 }
    Image{ width: 33.0 height: 25.0 margin: Inset{left: 271.0 right: 0 top: 226.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/5e7e1f003d0dd5c7.png") }
    View{ width: 30.6 height: 17.0 margin: Inset{left: 273.6 right: 0 top: 231.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "$139" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 345.0 height: 460.0 margin: Inset{left: 15.0 right: 0 top: 435.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 10.0 }
    RoundedView{ width: 22.1 height: 24.0 margin: Inset{left: 319.5 right: 0 top: 443.0 bottom: 0} draw_bg.color: #1c8ff800 }
    View{ width: 69.6 height: 17.0 margin: Inset{left: 38.0 right: 0 top: 449.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Transactions" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 345.0 height: 1.0 margin: Inset{left: 15.0 right: 0 top: 534.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 47.9 height: 16.0 margin: Inset{left: 299.3 right: 0 top: 509.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Payment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 53.6 height: 26.0 margin: Inset{left: 301.1 right: 0 top: 488.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "+ $85" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 51.1 height: 17.0 margin: Inset{left: 88.6 right: 0 top: 508.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "06:34AM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 79.3 height: 21.0 margin: Inset{left: 88.6 right: 0 top: 488.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Ryan Ellis" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 36.8 height: 40.0 margin: Inset{left: 33.4 right: 0 top: 485.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 18.4 }
    RoundedView{ width: 345.0 height: 1.0 margin: Inset{left: 15.0 right: 0 top: 594.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 47.1 height: 16.0 margin: Inset{left: 299.3 right: 0 top: 569.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Debit" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 53.6 height: 26.0 margin: Inset{left: 301.1 right: 0 top: 548.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "- $23" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 51.1 height: 17.0 margin: Inset{left: 88.6 right: 0 top: 568.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "08:54PM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 79.3 height: 21.0 margin: Inset{left: 88.6 right: 0 top: 548.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Max Carson" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 36.8 height: 40.0 margin: Inset{left: 33.4 right: 0 top: 545.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 18.4 }
    RoundedView{ width: 345.0 height: 1.0 margin: Inset{left: 15.0 right: 0 top: 654.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 47.1 height: 16.0 margin: Inset{left: 299.3 right: 0 top: 629.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Refund" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 53.6 height: 26.0 margin: Inset{left: 301.1 right: 0 top: 608.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "+ $31" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 51.1 height: 17.0 margin: Inset{left: 88.6 right: 0 top: 628.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "02:25PM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 79.3 height: 21.0 margin: Inset{left: 88.6 right: 0 top: 608.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Paul Mills" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 36.8 height: 40.0 margin: Inset{left: 33.4 right: 0 top: 605.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 18.4 }
    RoundedView{ width: 345.0 height: 1.0 margin: Inset{left: 15.0 right: 0 top: 774.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 47.9 height: 16.0 margin: Inset{left: 299.3 right: 0 top: 749.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Payment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 44.6 height: 26.0 margin: Inset{left: 301.1 right: 0 top: 728.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "+ $9" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 51.1 height: 17.0 margin: Inset{left: 88.6 right: 0 top: 748.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "06:34AM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 79.3 height: 21.0 margin: Inset{left: 88.6 right: 0 top: 728.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Ryan Ellis" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 36.8 height: 40.0 margin: Inset{left: 33.4 right: 0 top: 725.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 18.4 }
    RoundedView{ width: 345.0 height: 1.0 margin: Inset{left: 15.0 right: 0 top: 834.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 47.1 height: 16.0 margin: Inset{left: 299.3 right: 0 top: 809.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Debit" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 51.1 height: 17.0 margin: Inset{left: 88.6 right: 0 top: 808.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "08:54PM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 79.3 height: 21.0 margin: Inset{left: 88.6 right: 0 top: 788.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Max Carson" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 36.8 height: 40.0 margin: Inset{left: 33.4 right: 0 top: 785.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 18.4 }
    RoundedView{ width: 345.0 height: 1.0 margin: Inset{left: 15.0 right: 0 top: 894.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 47.1 height: 16.0 margin: Inset{left: 299.3 right: 0 top: 869.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Refund" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 44.6 height: 26.0 margin: Inset{left: 301.1 right: 0 top: 848.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "$24" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 51.1 height: 17.0 margin: Inset{left: 88.6 right: 0 top: 868.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "02:25PM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 79.3 height: 21.0 margin: Inset{left: 88.6 right: 0 top: 848.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Paul Mills" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 36.8 height: 40.0 margin: Inset{left: 33.4 right: 0 top: 845.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 18.4 }
    RoundedView{ width: 345.0 height: 1.0 margin: Inset{left: 15.0 right: 0 top: 714.0 bottom: 0} draw_bg.color: #f4f6f9ff }
    View{ width: 47.9 height: 16.0 margin: Inset{left: 299.3 right: 0 top: 689.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "Payment" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 6.2 } } }
    View{ width: 44.6 height: 26.0 margin: Inset{left: 301.1 right: 0 top: 668.0 bottom: 0} flow: Down align: Align{x: 1.0} Label{ width: Fit height: Fit text: "- $5" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 9.9 } } }
    View{ width: 51.1 height: 17.0 margin: Inset{left: 88.6 right: 0 top: 688.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "09:13PM" draw_text.color: #6c7b8aff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 93.6 height: 21.0 margin: Inset{left: 88.6 right: 0 top: 668.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Travis Lloyd" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.8 } } }
    RoundedView{ width: 36.8 height: 40.0 margin: Inset{left: 33.4 right: 0 top: 665.0 bottom: 0} draw_bg.color: #212b36ff draw_bg.border_radius: 18.4 }
    RoundedView{ width: 375.0 height: 90.0 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 375.0 height: 1.3 margin: Inset{left: 0.0 right: 0 top: 88.7 bottom: 0} draw_bg.color: #ffffff0e }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 331.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 8.3 height: 11.2 margin: Inset{left: 340.5 right: 0 top: 41.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/5c8e7d98cdefe72b.png") }
    Image{ width: 11.9 height: 11.5 margin: Inset{left: 335.3 right: 0 top: 45.4 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/b1fb585afc1f53b0.png") }
    Image{ width: 17.5 height: 22.5 margin: Inset{left: 334.5 right: 0 top: 40.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/9bb7e96c33b13c20.png") }
    RoundedView{ width: 24.0 height: 30.9 margin: Inset{left: 20.0 right: 0 top: 36.0 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 4.7 height: 12.2 margin: Inset{left: 26.0 right: 0 top: 45.6 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/5a2d601a49d66b9c.png") }
    View{ width: 148.9 height: 18.9 margin: Inset{left: 59.0 right: 0 top: 36.0 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Transaction history" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 8.1 } } }
    View{ width: 34.2 height: 17.0 margin: Inset{left: 226.9 right: 0 top: 109.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "week" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 34.2 height: 17.0 margin: Inset{left: 39.5 right: 0 top: 109.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "today" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 34.2 height: 17.0 margin: Inset{left: 133.4 right: 0 top: 109.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "Month" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    View{ width: 34.2 height: 17.0 margin: Inset{left: 320.9 right: 0 top: 109.5 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "day" draw_text.color: #140f26ff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 375.0 height: 75.0 margin: Inset{left: 0.0 right: 0 top: 737.0 bottom: 0} draw_bg.color: #121217ff }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 325.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff800 }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 250.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 15.5 height: 3.2 margin: Inset{left: 255.0 right: 0 top: 764.3 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/7d0aeb5d27aafc03.png") }
    Image{ width: 15.5 height: 17.1 margin: Inset{left: 255.0 right: 0 top: 754.8 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/1958cd140415fdaa.png") }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 175.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 12.8 height: 6.3 margin: Inset{left: 179.0 right: 0 top: 766.1 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/dbb5fb8dccce3ca2.png") }
    RoundedView{ width: 15.5 height: 18.4 margin: Inset{left: 191.0 right: 0 top: 746.5 bottom: 0} draw_bg.color: #4c5fefff draw_bg.border_radius: 3.5 }
    View{ width: 18.3 height: 18.2 margin: Inset{left: 193.2 right: 0 top: 750.0 bottom: 0} flow: Down align: Align{x: 0.5} Label{ width: Fit height: Fit text: "10" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-SemiBold.ttf") asc: 0.0 desc: 0.0 } } font_size: 5.6 } } }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 100.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 12.4 height: 11.7 margin: Inset{left: 107.0 right: 0 top: 760.8 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/e918d813d0aa7bbd.png") }
    RoundedView{ width: 24.0 height: 32.8 margin: Inset{left: 25.5 right: 0 top: 746.5 bottom: 0} draw_bg.color: #1c8ff800 }
    Image{ width: 375.0 height: 37.5 margin: Inset{left: 0.0 right: 0 top: 0.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/dbbd9db129e5adec.png") }
    RoundedView{ width: 1.1 height: 3.4 margin: Inset{left: 356.4 right: 0 top: 15.8 bottom: 0} draw_bg.color: #ffffff66 }
    RoundedView{ width: 14.4 height: 6.1 margin: Inset{left: 339.6 right: 0 top: 14.4 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 1.4 }
    Image{ width: 14.0 height: 9.9 margin: Inset{left: 319.0 right: 0 top: 12.5 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/f9e85dd1496baadf.png") }
    Image{ width: 15.0 height: 9.2 margin: Inset{left: 299.0 right: 0 top: 13.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/47adc1dc07e11640.png") }
    View{ width: 55.9 height: 16.0 margin: Inset{left: 25.0 right: 0 top: 14.5 bottom: 0} flow: Down align: Align{x: 0.0} Label{ width: Fit height: Fit text: "Atro UI" draw_text.color: #ffffffff draw_text.text_style: TextStyle{ font_family: FontFamily{ latin := FontMember{ res: crate_resource("makepad_widgets:resources/Montserrat-Medium.ttf") asc: 0.0 desc: 0.0 } } font_size: 7.4 } } }
    Image{ width: 375.0 height: 37.0 margin: Inset{left: 0.0 right: 0 top: 775.0 bottom: 0} fit: ImageFit.Stretch src: http_resource("http://127.0.0.1:8787/_icons/d5c153885dd141a3.png") }
    RoundedView{ width: 100.0 height: 4.0 margin: Inset{left: 137.5 right: 0 top: 798.0 bottom: 0} draw_bg.color: #ffffffff draw_bg.border_radius: 2.0 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 30.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
    RoundedView{ width: 24.0 height: 24.0 margin: Inset{left: 321.0 right: 0 top: 773.0 bottom: 0} draw_bg.color: #50a1ff00 }
}
