[package]
name = "octosense-wizard"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
serde_json = { version = "1", features = ["float_roundtrip"] }
makepad-widgets = { path = "../../../../../octosense-org/makepad/widgets" }
splash-widgets = { path = "../../../../../octosense-org/octoscript-makepad/crates/splash-widgets" }
splash-render = { path = "../../../../../octosense-org/octoscript-makepad/crates/splash-render" }
splash-makepad = { path = "../../../../../octosense-org/octoscript-makepad/crates/splash-makepad" }
splash-ui-l0 = { path = "../../../../../octosense-org/octoscript/crates/splash-ui-l0" }

[profile.release]
opt-level = 3
lto = false
codegen-units = 1

[[bin]]
name = "octosense-wizard"
path = "src/main.rs"
