#!/usr/bin/env python3
"""Emit native/src/icons.rs from the storyboard's SVG dictionary so the runtime
draws exactly the glyphs the reviewed atlas was rendered from."""
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
import design
out = ['//! The storyboard\'s vector icons (scripts/design.py SVG), generated by', '//! scripts/gen_icons.py — do not edit. Served to the renderer from the', '//! module\'s loopback asset server.', 'pub const ICONS: &[(&str, &str)] = &[']
for name, body in design.SVG.items():
    out.append(f'    ({name!r}, r##"{body}"##),'.replace("'", '"', 2))
out.append('];')
out.append('''
/// One stroked icon file in the given hex colour (`rrggbb`).
pub fn svg(name: &str, color: &str) -> Option<String> {
    let body = ICONS.iter().find(|(n, _)| *n == name)?.1.replace("currentColor", &format!("#{color}"));
    let viewbox = if name == "status" { "0 0 56 28" } else { "0 0 28 28" };
    Some(format!(r##"<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}" fill="none" stroke="#{color}" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">{body}</svg>"##))
}
''')
Path(__file__).resolve().parents[1].joinpath('native/src/icons.rs').write_text('\n'.join(out))
print(len(design.SVG), 'icons')
