#!/usr/bin/env python3
"""Emit the GLM app cards for the DEVICE-ASSEMBLED ArkUI path.

The Atro exhibit path (gen_ohos_atro.py main) bakes a whole theme chain into
each source on the workstation. This one does not: it writes the card text and
the lowered tree, and the phone splices palette -> delta -> axes -> derivations
-> kit itself (Splash-OH crates/splash-oh-native/src/theme.rs). Changing a
card's mood is then one word in the card, with nothing regenerated here.

The tree travels with live-data shims because the ArkUI path has no data
runtime of its own: they forward `sys.*` to the device's fetch capabilities.

    python3 gen_ohos_themed.py --kit camo --snapshot snap.json

Existed only as an inline script through the first live-data round, which is
why its two shim bugs (a `sys_news` arity that left every headline index nil,
and WMO codes reaching text nodes as bare numbers) survived a screenshot
review: there was no file to re-read.
"""
import json
import pathlib
import sys

import gen_ohos_atro as G

# (name, card path relative to lab/sketch) — the app cards a real model wrote.
CARDS = [
    ("GLM_Weather", "glm_weather.card"),
    ("GLM_News", "glm_news.card"),
    ("GLM_Weather_Atro", "glm_weather_atro.card"),
    ("GLM_News_Atro", "glm_news_atro.card"),
]

HERE = pathlib.Path(__file__).resolve().parent


def main():
    snap = {}
    if "--snapshot" in sys.argv:
        snap = json.loads(pathlib.Path(sys.argv[sys.argv.index("--snapshot") + 1]).read_text())
    out_dir = G.OH / "assets" / "atro"
    out_dir.mkdir(parents=True, exist_ok=True)

    rows = []
    for name, rel in CARDS:
        card_path = HERE / rel
        if not card_path.exists():
            print(f"{name}: MISSING {card_path}")
            continue
        _card, body = G.emit_themed(name, card_path, snap, out_dir)
        rows.append(
            f'    ("{name}", include_str!("../assets/atro/{name}.card.txt"),\n'
            f'     include_str!("../assets/atro/{name}.tree.splash")),')
        print(f"{name}: {len(body) // 1000}KB tree")

    gen = G.OH / "src" / "themed_screens.rs"
    gen.write_text(
        "// GENERATED by octos-one/lab/sketch/gen_ohos_themed.py — do not edit.\n"
        "/// Cards whose THEME the device assembles: (name, card source, lowered tree).\n"
        "pub const THEMED_SCREENS: &[(&str, &str, &str)] = &[\n"
        + "\n".join(rows) + "\n];\n")
    print(f"wrote {gen}")


if __name__ == "__main__":
    main()
